apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-cni
  namespace: kube-system
  labels:
    app: azure-cni
spec:
  selector:
    matchLabels:
      k8s-app: azure-cni
  template:
    metadata:
      labels:
        k8s-app: azure-cni
      annotations:
        cluster-autoscaler.kubernetes.io/daemonset-pod: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/cluster
                operator: Exists
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
              - key: kubernetes.io/os
                operator: In
                values:
                - windows
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\system"
      hostNetwork: true
      serviceAccountName: azure-cni
      priorityClassName: system-node-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: "Exists"
          effect: NoExecute
        - operator: "Exists"
          effect: NoSchedule
      initContainers:
        - name: azure-cni-windows
          image:  mcr.microsoft.com/containernetworking/cni-dropgz:v0.0.4
          imagePullPolicy: Always
          command: ["/dropgz"]
          args:
            - deploy
            - azure-vnet
            - -o
            - /k/azurecni/bin/
            - azure.conflist
            - -o
            - /k/azurecni/netconf/
          volumeMounts:
            - name: cni-bin
              mountPath: /k/azurecni/bin/
            - name: cni-conflist
              mountPath: /k/azurecni/netconf/
      containers:
        - name: cni-windows-multitenancy
          image: acndev.azurecr.io/cni-test-windows:latest
          imagePullPolicy: Always
      volumes:
        - name: cni-conflist
          hostPath:
            path: /k/azurecni/netconf/
            type: DirectoryOrCreate
        - name: cni-bin
          hostPath:
            path: /k/azurecni/bin
            type: DirectoryOrCreate
