parameters:
  name: ""
  displayName: ""
  clusterType: ""
  clusterName: ""
  vmSize: ""
  k8sVersion: ""
  dependsOn: ""

stages:
  - stage: ${{ parameters.clusterName }}
    displayName: ${{ parameters.displayName }} - Create Cluster
    dependsOn:
      - ${{ parameters.dependsOn }}
      - setup
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
      IMAGE_REPO_PATH: $[ stageDependencies.setup.env.outputs['EnvironmentalVariables.imageRepositoryPath'] ]
      AZURE_IPAM_VERSION: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.azureIpamVersion'] ]
      CNI_VERSION: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.cniVersion'] ]
      CNS_VERSION: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.cnsVersion'] ]
      IPAM_IMAGE_NAME_OVERRIDE: $(IMAGE_REPO_PATH)/azure-ipam
      CNS_IMAGE_NAME_OVERRIDE: $(IMAGE_REPO_PATH)/cns
      CNI_IMAGE_NAME_OVERRIDE: $(IMAGE_REPO_PATH)/cni
      IPAM_IMAGE_REPO: ACN
      CNS_IMAGE_REPO: ACN
      CNI_IMAGE_REPO: ACN
    jobs:
      - job: ${{ parameters.name }}
        displayName: Cluster - ${{ parameters.name }}
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          isCustom: true
          type: linux
        steps:
          - checkout: azure-container-networking
          - template: ../../templates/create-cluster-steps.yaml
            parameters:
              clusterType: ${{ parameters.clusterType }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              vmSize: ${{ parameters.vmSize }}
              k8sVersion: ${{ parameters.k8sVersion }}
              region: $(REGION_AKS_CLUSTER_TEST)
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                set -e

                windows_nodepool=$(az aks nodepool list \
                --resource-group ${{ parameters.clusterName }}-$(commitID) \
                --cluster-name ${{ parameters.clusterName }}-$(commitID) \
                --query "[?osType=='Windows']" \
                --output tsv)

                if [ -z "$windows_nodepool" ]; then
                  echo "No Windows node pool found in the AKS cluster."
                  while true; do
                    cluster_state=$(az aks show \
                    --name "${{ parameters.clusterName }}-$(commitID)" \
                    --resource-group "${{ parameters.clusterName }}-$(commitID)" \
                    --query provisioningState)
                    if echo "$cluster_state" | grep -q "Updating"; then
                      echo "Cluster is updating. Sleeping for 30 seconds..."
                      sleep 30
                    else
                      break
                    fi
                  done
                  echo "Cluster state is: $cluster_state"
                  make -C ./hack/aks set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(commitID)
                  make -C ./hack/aks windows-nodepool-up AZCLI=az SUB=$(SUB_AZURE_NETWORK_AGENT_BUILD_VALIDATIONS) CLUSTER=${{ parameters.clusterName }}-$(commitID) VM_SIZE_WIN=${{ parameters.vmSize }}
                  echo "Windows node was successfully added"
                  kubectl cluster-info
                  kubectl get node -owide
                  kubectl get po -owide -A
                else
                  echo "Windows node pool already exists in the AKS cluster."
                fi
            name: "Add_Windows_Node"
            displayName: "Add windows node to cluster"
            retryCountOnTaskFailure: 5
          - template: ../../templates/network-install.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              networkType: azure-cni-overlay-stateless
              azureIpamVersion: $(AZURE_IPAM_VERSION)
              cnsVersion: $(CNS_VERSION)
              cniVersion: $(CNI_VERSION)
              installFlag: INSTALL_AZURE_VNET_STATELESS
              os: windows

  - stage: ${{ parameters.name }}
    displayName: E2E-${{ parameters.displayName }}
    dependsOn:
    - setup
    - ${{ parameters.clusterName }}
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
      IMAGE_REPO_PATH: $[ stageDependencies.setup.env.outputs['EnvironmentalVariables.imageRepositoryPath'] ]
      GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
      GOBIN: "$(GOPATH)/bin" # Go binaries path
      modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"

      AZURE_IPAM_VERSION: $[ stageDependencies.setup.env.outputs['EnvironmentalVariables.azureIpamVersion'] ]
      CNI_VERSION: $[ stageDependencies.setup.env.outputs['EnvironmentalVariables.cniVersion'] ]
      CNS_VERSION: $[ stageDependencies.setup.env.outputs['EnvironmentalVariables.cnsVersion'] ]
      IPAM_IMAGE_NAME_OVERRIDE: $(IMAGE_REPO_PATH)/azure-ipam
      CNS_IMAGE_NAME_OVERRIDE: $(IMAGE_REPO_PATH)/cns
      CNI_IMAGE_NAME_OVERRIDE: $(IMAGE_REPO_PATH)/cni
    jobs:
      - job: ${{ parameters.name }}_windows
        displayName: Azure Stateless CNI Overlay Test Suite | Windows - (${{ parameters.name }})
        timeoutInMinutes: 120
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands:
          - agent.os -equals Linux
          - Role -equals $(CUSTOM_E2E_ROLE)
          isCustom: true
          type: linux
        steps:
          - checkout: azure-container-networking
          - template: azure-cni-overlay-stateless-e2e.steps.yaml
            parameters:
              name: ${{ parameters.name }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: windows
              vmSizeWin: ${{ parameters.vmSize }}

      - template: ../../cni/k8s-e2e/k8s-e2e.jobs.yaml
        parameters:
          sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          os: windows
          dependsOn: ${{ parameters.name }}_windows
          datapath: true
          dns: true
          portforward: true
          hostport: true
          service: true
          hybridWin: true

      - job: failedE2ELogs_windows
        displayName: "Windows Failure Logs"
        dependsOn:
          - ${{ parameters.name }}_windows
          - cni_windows
        condition: in(dependencies.${{ parameters.name }}_windows.result, 'Failed')
        pool:
          type: linux
        variables:
          ob_outputDirectory: $(Build.ArtifactStagingDirectory)/out
        steps:
          - checkout: azure-container-networking
          - template: ../../templates/log.steps.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: windows
              cni: cniv2
