pr: none
trigger: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight Cilium with Hubble
  branches:
    include:
    - master

variables:
  clustername: cilium-$(Build.BuildId)
  cilium_version: v1.14.4

stages:
  - template: ./stack/stack-template.yaml
    parameters:
      clusterName: $(clustername)-singlestack
      clusterType: overlay-byocni-nokubeproxy-up
      ciliumconfig: cilium-config-hubble
      displayName: Cilium on AKS Overlay with Hubble Enabled
      name: cilium_overlay_hubble
      cilium_version: $(cilium_version)
      stack: singlestack
      region: $(REGION_AKS_CLUSTER_TEST)
  - template: ./stack/stack-template.yaml
    parameters:
      clusterName: $(clustername)-dualstack
      clusterType: dualstack-byocni-nokubeproxy-up
      ciliumconfig: cilium-config-hubble-dual
      displayName: Cilium on AKS Overlay dualstack with Hubble Enabled
      name: cilium_overlay_hubble_dualstack
      cilium_version: $(cilium_version)
      stack: dualstack
      region: $(REGION_DUALSTACKOVERLAY_CLUSTER_TEST)