pr: none
trigger: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight Cilium with Hubble
  branches:
    include:
    - master

variables:
  clustername: ciliumhubble-$(Build.SourceBranchName)-$(Build.BuildId)
  cilium_version: v1.14.4

stages:
  - template: ./stack/stack-template.yaml
    parameters:
      clusterName: $(clustername)
      clusterType: overlay-byocni-nokubeproxy-up
      cilium-config: cilium-config-hubble
      displayName: Cilium on AKS Overlay with Hubble Enabled
      name: cilium_overlay_hubble
      cilium_version: $(cilium_version)
      stack: ipv4
  - template: ./stack/stack-template.yaml
    parameters:
      clusterName: $(clustername)
      clusterType: dualstack-byocni-nokubeproxy-up
      cilium-config: cilium-config-hubble-dual
      displayName: Cilium on AKS Overlay dualstack with Hubble Enabled
      name: cilium_overlay_hubble_dualstack
      cilium_version: $(cilium_version)
      stack: ipv4-ipv6