# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "ci"
  labels: [ "ci", "dependencies" ]
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "ci"
  labels: [ "ci", "dependencies" ]
  open-pull-requests-limit: 10
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies" ]
  open-pull-requests-limit: 10
  ignore:
    # Constrain Kubernetes dependencies to v1.31 ±1 compatibility (v1.30-v1.32)
    - dependency-name: "k8s.io/api"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.33.0", "<0.30.0"]
- package-ecosystem: "gomod"
  directory: "/azure-ipam"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "azure-ipam" ]
  open-pull-requests-limit: 10
  ignore:
    # Constrain Kubernetes dependencies to v1.31 ±1 compatibility (v1.30-v1.32)
    - dependency-name: "k8s.io/api"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.33.0", "<0.30.0"]
- package-ecosystem: "gomod"
  directory: "/build/tools"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies" ]
  open-pull-requests-limit: 10
  ignore:
    # Constrain Kubernetes dependencies to v1.31 ±1 compatibility (v1.30-v1.32)
    - dependency-name: "k8s.io/api"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.33.0", "<0.30.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.33.0", "<0.30.0"]
- package-ecosystem: "gomod"
  directory: "/dropgz"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "dropgz" ]
  open-pull-requests-limit: 10
- package-ecosystem: "gomod"
  directory: "/zapai"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies" ]
  open-pull-requests-limit: 10

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "release/1.5" ]
  open-pull-requests-limit: 10
  target-branch: "release/v1.5"
  ignore:
    # Constrain Kubernetes dependencies to v1.29 ±1 compatibility (v1.28-v1.30)
    - dependency-name: "k8s.io/api"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.31.0", "<0.28.0"]
- package-ecosystem: "gomod"
  directory: "/azure-ipam"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "azure-ipam", "release/1.5" ]
  open-pull-requests-limit: 10
  target-branch: "release/v1.5"
  ignore:
    # Constrain Kubernetes dependencies to v1.29 ±1 compatibility (v1.28-v1.30)
    - dependency-name: "k8s.io/api"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.31.0", "<0.28.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.31.0", "<0.28.0"]
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "release/1.4" ]
  open-pull-requests-limit: 10
  target-branch: "release/v1.4"
  ignore:
    # Constrain Kubernetes dependencies to v1.26 ±1 compatibility (v1.25-v1.27)
    - dependency-name: "k8s.io/api"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.28.0", "<0.25.0"]
- package-ecosystem: "gomod"
  directory: "/azure-ipam"
  schedule:
    interval: "daily"
  reviewers:
    - "azure/azure-sdn-members"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "azure-ipam", "release/1.4" ]
  open-pull-requests-limit: 10
  target-branch: "release/v1.4"
  ignore:
    # Constrain Kubernetes dependencies to v1.26 ±1 compatibility (v1.25-v1.27)
    - dependency-name: "k8s.io/api"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.28.0", "<0.25.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.28.0", "<0.25.0"]
