# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "ci"
  labels: [ "ci", "dependencies" ]
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "ci"
  labels: [ "ci", "dependencies" ]
  open-pull-requests-limit: 10


# Constrain Kubernetes dependencies to compatibility with default branch - v1.33-v1.35
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies" ]
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "k8s.io/api"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.35.0"]
- package-ecosystem: "gomod"
  directory: "/azure-ipam"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "azure-ipam" ]
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "k8s.io/api"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.35.0"]
- package-ecosystem: "gomod"
  directory: "/build/tools"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies" ]
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "k8s.io/api"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.35.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.35.0"]
- package-ecosystem: "gomod"
  directory: "/dropgz"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "dropgz" ]
  open-pull-requests-limit: 10
- package-ecosystem: "gomod"
  directory: "/zapai"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies" ]
  open-pull-requests-limit: 10


# Constrain Kubernetes dependencies to compatibility with release/v1.6 branch - v1.30-v1.32
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "release/1.6"  ]
  open-pull-requests-limit: 10
  target-branch: "release/v1.6"
  ignore:
    - dependency-name: "k8s.io/api"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.32.0"]
- package-ecosystem: "gomod"
  directory: "/azure-ipam"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "azure-ipam", "release/1.6" ]
  open-pull-requests-limit: 10
  target-branch: "release/v1.6"
  ignore:
    - dependency-name: "k8s.io/api"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.32.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.32.0"]


# Constrain Kubernetes dependencies to compatibility with release/v1.5 branch - v1.28-v1.30
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "release/1.5" ]
  open-pull-requests-limit: 10
  target-branch: "release/v1.5"
  ignore:
    - dependency-name: "k8s.io/api"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.30.0"]
- package-ecosystem: "gomod"
  directory: "/azure-ipam"
  schedule:
    interval: "daily"
  commit-message:
    prefix: "deps"
  labels: [ "dependencies", "azure-ipam", "release/1.5" ]
  open-pull-requests-limit: 10
  target-branch: "release/v1.5"
  ignore:
    - dependency-name: "k8s.io/api"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/apiextensions-apiserver"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/apimachinery"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/client-go"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/kubelet"
      versions: [">=0.30.0"]
    - dependency-name: "k8s.io/kubectl"
      versions: [">=0.30.0"]
