issues:
  max-same-issues: 0
  max-issues-per-linter: 0
linters:
  exclusions:
    paths:
      - bpf-prog/block-iptables/pkg/
  presets: 
  - bugs
  - error
  - format
  - performance
  - unused
  enable:
  - copyloopvar
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goprintffuncname
  - gosimple
  - lll
  - misspell
  - nakedret
  - promlinter
  - revive
linters-settings:
  gocritic:
    enabled-tags:
    - "diagnostic"
    - "style"
    - "performance"
    disabled-checks:
    - "hugeParam"
  govet:
    enable:
    - shadow
  lll:
    line-length: 200
