version: "2"
linters:
  enable:
    - copyloopvar
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - lll
    - misspell
    - nakedret
    - promlinter
    - revive
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
    govet:
      enable:
        - shadow
    lll:
      line-length: 200
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
formatters:
  enable:
    - gofmt
