apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kapinger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapinger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kapinger
        server: good
    spec:
      containers:
      - env:
        - name: TARGET_TYPE
          value: service
        - name: HTTP_PORT
          value: "8080"
        - name: TCP_PORT
          value: "8085"
        - name: UDP_PORT
          value: "8086"
        image: acnpublic.azurecr.io/kapinger:be57650
        name: kapinger
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 20Mi
          requests:
            memory: 20Mi
status: {}
