// Code generated by MockGen. DO NOT EDIT.
// Source: /root/go/src/github.com/Azure/azure-container-networking/cns/multitenantcontroller/multitenantoperator/multitenantcrdreconciler.go

// Package mockclients is a generated GoMock package.
package mockclients

import (
	reflect "reflect"

	cns "github.com/Azure/azure-container-networking/cns"
	types "github.com/Azure/azure-container-networking/cns/types"
	gomock "github.com/golang/mock/gomock"
)

// Mockcnsrestservice is a mock of cnsrestservice interface.
type Mockcnsrestservice struct {
	ctrl     *gomock.Controller
	recorder *MockcnsrestserviceMockRecorder
}

// MockcnsrestserviceMockRecorder is the mock recorder for Mockcnsrestservice.
type MockcnsrestserviceMockRecorder struct {
	mock *Mockcnsrestservice
}

// NewMockcnsrestservice creates a new mock instance.
func NewMockcnsrestservice(ctrl *gomock.Controller) *Mockcnsrestservice {
	mock := &Mockcnsrestservice{ctrl: ctrl}
	mock.recorder = &MockcnsrestserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcnsrestservice) EXPECT() *MockcnsrestserviceMockRecorder {
	return m.recorder
}

// CreateOrUpdateNetworkContainerInternal mocks base method.
func (m *Mockcnsrestservice) CreateOrUpdateNetworkContainerInternal(arg0 *cns.CreateNetworkContainerRequest) types.ResponseCode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateNetworkContainerInternal", arg0)
	ret0, _ := ret[0].(types.ResponseCode)
	return ret0
}

// CreateOrUpdateNetworkContainerInternal indicates an expected call of CreateOrUpdateNetworkContainerInternal.
func (mr *MockcnsrestserviceMockRecorder) CreateOrUpdateNetworkContainerInternal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateNetworkContainerInternal", reflect.TypeOf((*Mockcnsrestservice)(nil).CreateOrUpdateNetworkContainerInternal), arg0)
}

// DeleteNetworkContainerInternal mocks base method.
func (m *Mockcnsrestservice) DeleteNetworkContainerInternal(arg0 cns.DeleteNetworkContainerRequest) types.ResponseCode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetworkContainerInternal", arg0)
	ret0, _ := ret[0].(types.ResponseCode)
	return ret0
}

// DeleteNetworkContainerInternal indicates an expected call of DeleteNetworkContainerInternal.
func (mr *MockcnsrestserviceMockRecorder) DeleteNetworkContainerInternal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetworkContainerInternal", reflect.TypeOf((*Mockcnsrestservice)(nil).DeleteNetworkContainerInternal), arg0)
}

// GetNetworkContainerInternal mocks base method.
func (m *Mockcnsrestservice) GetNetworkContainerInternal(arg0 cns.GetNetworkContainerRequest) (cns.GetNetworkContainerResponse, types.ResponseCode) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkContainerInternal", arg0)
	ret0, _ := ret[0].(cns.GetNetworkContainerResponse)
	ret1, _ := ret[1].(types.ResponseCode)
	return ret0, ret1
}

// GetNetworkContainerInternal indicates an expected call of GetNetworkContainerInternal.
func (mr *MockcnsrestserviceMockRecorder) GetNetworkContainerInternal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkContainerInternal", reflect.TypeOf((*Mockcnsrestservice)(nil).GetNetworkContainerInternal), arg0)
}
