codecov:
  token: a182352a-07e1-4870-be05-daac46237b76
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        threshold: 0.5
    patch:
      default:
        threshold: 0.5
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
