---
apiVersion: v1
kind: Service
metadata:
  name: npm-controller-metrics-cluster-service
  namespace: kube-system
  labels:
    app: azure-npm 
    component: controller
spec:
  selector:
    k8s-app: azure-npm
    component: controller
  ports:
    - port: 9000
      targetPort: 10091
