parameters:
- name: arch
  type: string
  values:
  - amd64
  - arm64

- name: os
  type: string
  values:
  - windows
  - linux

- name: images
  type: object


jobs:
- ${{ each image in parameters.images }}:
  - job: ${{ image }}_${{ parameters.os }}_${{ parameters.arch }}
    displayName: Build Images
    pool:
      arch: ${{ parameters.arch }}
      os: ${{ parameters.os }}
      ${{ if eq(parameters.os, 'windows') }}:
        name: $(BUILD_POOL_NAME_DEFAULT_WINDOWS)
      ${{ elseif eq(parameters.os, 'linux') }}:
        ${{ if eq(parameters.arch, 'amd64') }}:
          name: $(BUILD_POOL_NAME_DEFAULT)
        ${{ elseif eq(parameters.arch, 'arm64') }}:
          name: $(BUILD_POOL_NAME_LINUX_ARM64)
  
    templateContext:
      type: containerBuildJob
      arguments:
        image: $(IMAGE_NAME_AND_TAG_${{ parameters.name }})
        dockerfile: $(DOCKERFILE_PATH_${{ parameters.name }})
        path: $(BUILD_CONTEXT_${{ parameters.name }})
        buildArguments: TARGET=${{ parameters.os }} OS=${{ parameters.os }} PLATFORM=${{ parameters.os }} ARCH=${{ parameters.arch }} $(EXTRA_BUILD_ARGS_${{ parameters.name }})
        enableNetwork: true                         # Optional. Default: false
        enablePull: false                           # Optional. Default: true
        enableCache: true                           # Optional. Default: false
        useBuildKit: true

    steps:
    - task: GoTool@0
      inputs:
        version: $(GO_VERSION)
    - bash: |
        set -e
    
        BUILD_CONTEXT=$(make "$MAKE_BUILD_CONTEXT")
        echo >&2 "##vso[task.setvariable variable=BUILD_CONTEXT_${VAR_ID};]$BUILD_CONTEXT"
    
        IMAGE_NAME_AND_TAG=$(make "$MAKE_IMG_NAME_AND_TAG")
        echo >&2 "##vso[task.setvariable variable=IMAGE_NAME_AND_TAG_${VAR_ID};]$IMAGE_NAME_AND_TAG"
    
        DOCKERFILE_PATH=$(make "$MAKE_DOCKERFILE_PATH")
        echo >&2 "##vso[task.setvariable variable=DOCKERFILE_PATH_${VAR_ID};]$DOCKERFILE_PATH"
    
        EXTRA_BUILD_ARGS=$(make "$MAKE_EXTRA_BUILD_ARGS")
        echo >&2 "##vso[task.setvariable variable=EXTRA_BUILD_ARGS_${VAR_ID};]$EXTRA_BUILD_ARGS"
      displayName: "Get Image Name"
      env:
        VAR_ID: ${{ parameters.name }}
        MAKE_BUILD_CONTEXT: ${{ parameters.name }}-image-build-context
        MAKE_IMG_NAME_AND_TAG: ${{ parameters.name }}-image-name-and-tag
        MAKE_DOCKERFILE_PATH: ${{ parameters.name }}-image-dockerfile-path
        MAKE_EXTRA_BUILD_ARGS: ${{ parameters.name }}-image-build-args
