parameters:

- name: images
  type: object
  default: []

- name: targetOs
  type: string
  default: linux
  values:
  - linux
  - windows

- name: targetArch
  type: string
  default: amd64
  values:
  - amd64
  - arm64

- name: buildOs
  type: string
  default: linux
  values:
  - linux
  - windows

- name: buildArch
  type: string
  default: amd64
  values:
  - amd64
  - arm64

- name: buildVariablesStepTemplate
  type: string
  default: ''


jobs:
- ${{ each imageName in parameters.images }}:
  - job: ${{ replace(concat(imageName, '_', parameters.targetOs, '_', parameters.targetArch), '-', '_') }}
    displayName: Build Image - (${{ imageName }} ${{ parameters.targetOs }}/${{ parameters.targetArch }})
    variables: 
      buildPlatform: ${{ parameters.buildOs }}/${{ parameters.buildArch }}
      targetPlatform: ${{ parameters.targetOs }}/${{ parameters.targetArch }}
    steps:
    - checkout: self

    - task: GoTool@0
      inputs:
        version: $(GO_VERSION)


    # Requires creation of the following variables:
    # - IMAGE_NAME_AND_TAG_${image}_${OS}_${ARCH}}
    # - DOCKERFILE_PATH_${image}_${OS}_${ARCH}}
    # - IMAGE_PLATFORM_TAG_${image}_${OS}_${ARCH}}
    # - EXTRA_BUILD_ARGS_$${image}_${OS}_${ARCH}}
    - ${{ if parameters.buildVariablesStepTemplate }}:
      - template: ${{ parameters.buildVariablesStepTemplate }}
        parameters:
          targetOs: ${{ parameters.targetOs }}
          targetArch: ${{ parameters.targetArch }}
          image: ${{ imageName }}


    - template: ./container-template.steps.yaml
      parameters:
        imageNameAndTag: $(IMAGE_NAME_AND_TAG_${{ imageName }}_${{ parameters.targetOs }}_${{ parameters.targetArch }})
        dockerfilePath: $(DOCKERFILE_PATH_${{ imageName }}_${{ parameters.targetOs }}_${{ parameters.targetArch }})
        buildContextPath: $(Build.SourcesDirectory)
        buildPlatform: $(buildPlatform)
        buildArch: ${{ parameters.buildArch }}
        buildOs: ${{ parameters.buildOs }}
        targetVersion: $(IMAGE_PLATFORM_TAG_${{ imageName }}_${{ parameters.targetOs }}_${{ parameters.targetArch }})
        targetPlatform: $(targetPlatform)
        targetOs: ${{ parameters.targetOs }}
        addBuildArgs: $(EXTRA_BUILD_ARGS_${{ imageName }}_${{ parameters.targetOs }}_${{ parameters.targetArch }})
