apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: azure-npm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: azure-npm
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: azure-npm-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-npm
subjects:
- kind: ServiceAccount
  name: azure-npm
  namespace: kube-system
---
apiVersion: v1
data:
  azure-npm.json: |
    {
        "ResyncPeriodInMinutes": 15,
        "ListeningPort":         10091,
        "ListeningAddress":      "0.0.0.0",
        "Toggles": {
            "EnablePrometheusMetrics": true,
            "EnablePprof":             true,
            "EnableHTTPDebugAPI":      true,
            "EnableV2NPM":             false,
            "PlaceAzureChainFirst":    false
        },
        "Transport": {
          "Address": "azure-npm.kube-system.svc.cluster.local",
          "Port": 10092,
          "ServicePort": 9001
        }
    }
kind: ConfigMap
metadata:
  name: azure-npm-config
  namespace: kube-system
---
apiVersion: v1
data:
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZzekNDQTV1Z0F3SUJBZ0lVYXU0eF
    E3QlMxeDgvWDc4UUdEMUFPbjJ4Y3dzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FURUxNQWtH
    QTFVRUJoTUNWVk14RXpBUkJnTlZCQWdNQ2xkaGMyaHBibWQwYjI0eEVEQU9CZ05WQkFjTQ
    pCMUpsWkcxdmJtUXhFakFRQmdOVkJBb01DVTFwWTNKdmMyOW1kREVPTUF3R0ExVUVDd3dG
    UVhwMWNtVXhEekFOCkJnTlZCQU1NQm01d2JTMWpZVEFlRncweU1qQXlNalF4T1RBeU1UVm
    FGdzB5TXpBeU1qUXhPVEF5TVRWYU1Ha3gKQ3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFR
    SURBcFhZWE5vYVc1bmRHOXVNUkF3RGdZRFZRUUhEQWRTWldSdApiMjVrTVJJd0VBWURWUV
    FLREFsTmFXTnliM052Wm5ReERqQU1CZ05WQkFzTUJVRjZkWEpsTVE4d0RRWURWUVFECkRB
    WnVjRzB0WTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUU
    NqbDRwdVBYb1cKQ3JrRFJKRU41aVUzT28zd2MwWDM3YlNGeG1qaFRzQXoxSS9ucG93ek0x
    VUpnMEY1eCt0a1U2QVE1VjJlYnZ0ZAptTTNqZXRvaDFoWXpHZmdFRXJLemRmNkhvUytFWF
    dDbjFoRDBtUTRVdWtRNVBWZklacU9jMlZ0NlZPdFd0V1NaCkRRQW9qSkFpS20zbDNXbmQ4
    VEwxb2NyNG93Z0ErZjNmRlpVaEhkekpQMFRJanBqZ3NCb3huNUsvMUxkNTFFcGIKMGt6YT
    RnaHpQYmxxTHBkb3Z5dkJ4ZEV5amdsYTBBZG9UNExsa0IvOXR5eSszb0NVZlNSaXZQYTJK
    VGJXWVY2SAp1M1RSSkVLQXE0djJKbjFTSklCQW1jaklQamE2cXZtRnVLbThQNzYvMHNuSi
    9zNGpNY0ZwSXB6eXRTWkZvZ2xnClZhL0h0Vmc1S2JLY25RNEtRT00yeE92YnRnZkg0eDNo
    cGVtSmJ6YVVjMmR0TzZuSk16ZG1CN1FNV2thYklTSkoKUythT0kwTllqc1RVNldwY0M2Zm
    VQY0lWYXkva25XR0lXTDB3ZHhvalNQRWhnMUU1WTlxVUplYVFod1pFVG1iMApCek91cm9x
    ajdMalM0K00xbWdxRFkxdHdOWWVQbHhtSzlyRDNhVkdLS3JMWWswRVhTSTFYRDJxNDlIRT
    JPQnV6CjY3L1JURVRKUVp5aklSZjk3anU3RXBvYjNXZWUrQWtVY1NBYnlDYlVGL0VNVHhP
    aE5NTElrQ3NkTXRZKzVXakkKVTNGZm1ZeW1UV2VjWmlQMmJWalUrQ2p2QXZ4NnNmSjk5WH
    BEaG9Kdjd4RXNjWmQ0YXhzWldYSlJaVzFvc2NzVwpkcXVDa3orR3NCRXVLODl2ZTlJdmZ0
    OVpwL0VDRkxVc1FRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVlZW9ECmRSQmZEc1RTcl
    M2OUNITEQ0REo0U3hnd0h3WURWUjBqQkJnd0ZvQVVlZW9EZFJCZkRzVFNyUzY5Q0hMRDRE
    SjQKU3hnd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQW
    dFQUM1RDZpQzl6TktJSgpoUmc4clpDYkZRN0Uwd1IyZVdUQ2x6VC8rWldUeHVDM3JKdVBk
    clZSNnBXVEJIMVpiWGNhYjF6bzhGZm16MkQ1Cld3VjBoQUh6UWVUdk1la3E5VDNLVWxnL0
    Vqa2pwckUrc29MaC9iR3R3Sk1MVnBZbURNOGJ3bFBxYlhVSTZYVmoKM3R4U1NYVFQxL0Jw
    QVZDYnoyVmRIQ1ZNcXJTSiswNVRzOFlmVFV0YmordHJURWdTbk8rWDhVQWF4VXkxVUgxdQ
    ozempWbUFKa0xnMk1NRUhKUXJpc0Vxb3JVdTZxQVc3WStKN2Z2ekpNYy8wU2Zha1g1Zmln
    OTEzbzFVb3B4L1lkCnI4TFE0NHBHUTZnNXlnRU5tZy90R0d4N0hGUzhiUnU4RU9ZcWFyYn
    RQU2JpeDVxU2ZaY0d5Rlhld3Iyc0RiRFYKN1YwNHEzMWdFMmZsSDg1ZU5VcXd4dnJMVXBz
    RHNBREwxYllldWJXRkRvOThUOTNlYk5oM3F1cXBubGxPempBaQpmQmY0NjNiTnNyeEc1ZV
    NjVDBleDRTZmRaY0VpdEJsVE80bExURm1lNWJpOElsSWlmcFdISCtGZGFuZXFkUGRRCjR5
    Z25veEZKWWVISGs4MUZZNnk4Y0NDbnpxTXVwdWtSUnNvNkJDSFloYVZPVzhSalVkODFacD
    g1NUhRVHY0S1IKU1JCOWQ4cUxDNUpJN1drdGVwYnpJUldMTVZWYTQ0TnBCdU0vQk1yclpT
    SUJNQkhBdWJORDdHekFtQUlXWFZnVwpTemVHVERZK2ZKTW9sRjZtL0N0Uk0zWFlhbGVjUG
    VIcHFSb1BFOEVoVXNkVU45RWNWeEpRRHQ5VGtmbXdmajZPCnk4Vk83bDhpR0pvb2pNVER3
    cGRXbDg1TndCTmpWRVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  name: npm-ca-certs
type: Opaque
---
apiVersion: v1
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZYVENDQTBVQ0ZHR005NEJPMUo4Sz
    JGM1F5eFlpQnowUGtWbytNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1Ha3gKQ3pBSkJnTlZCQVlU
    QWxWVE1STXdFUVlEVlFRSURBcFhZWE5vYVc1bmRHOXVNUkF3RGdZRFZRUUhEQWRTWldSdA
    piMjVrTVJJd0VBWURWUVFLREFsTmFXTnliM052Wm5ReERqQU1CZ05WQkFzTUJVRjZkWEps
    TVE4d0RRWURWUVFECkRBWnVjRzB0WTJFd0hoY05Nakl3TWpJME1Ua3dOalU1V2hjTk1qTX
    dNakkwTVRrd05qVTVXakJ0TVFzd0NRWUQKVlFRR0V3SlZVekVUTUJFR0ExVUVDQXdLVjJG
    emFHbHVaM1J2YmpFUU1BNEdBMVVFQnd3SFVtVmtiVzl1WkRFUwpNQkFHQTFVRUNnd0pUV2
    xqY205emIyWjBNUTR3REFZRFZRUUxEQVZCZW5WeVpURVRNQkVHQTFVRUF3d0tibkJ0CkxY
    TmxjblpsY2pDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTG
    1FQnh6b3hVeEkKZHVhM3JIa2JnWlorcER6MFQxYmM1cGJBSHNPREtIOVVGbVRYdFhtT0ZX
    Q1cxRkR3MHc3a2pnclYzaTQwQXJXOApNTWF0QU1LbXBXNzN3WkVDTzhpZHcvRkZDQnRyU3
    FhNlN2Z0VMVWdOSUFkNWw4YVduWW5tVFlRZS9MOW5UaEkzCnd6eCtOT2prcFc4elo1aUxI
    K294bVlmTjFBOWI3VnFzMFlkYnNiN0Z0eUtWbER5bDZCeEF2N0p1S0ZoSWFEdWkKMFNOTn
    B6RzVZM0xOSVIxYVIwdStzRFRNL3dCL0tkLzlQZDRLb2krYTVIMXlVampNNG5HOTg1QkJj
    TUR5bUJtdgp0SGZNUitlcTgxdm14T0FldlA4dGJEQk4vT2x0TFQ0dWtMdFdSa0s3Yk5Nd1
    VWOGtTQzdPcWVNMGVoME1kQWM0ClVmN1Z6UTVtNnJ6WGhWOTNjZnBaQitWRGZuR1ZRYyt6
    bFBkYkNtb2orNWdHMEVBME9ObFB0azFGMGd0ZlVBZ2EKQi9VSkJQTGFLOHZSb3NiL1hwV1
    ozYXhnaUJnOC9SeW51dlpMaE5xNldjV0ZMcVJmdXVSc0V4QTlqdysvVnd3Sgp2dk83bEVo
    c0dtMFhSQk1OVmQxRSthemxmd2poNlExVmVmdXNxTWNxUk9EYXY0Sk5IMWZYRmdRUFFrMF
    ZTd09zCnh4Y1Y4dXRjbXErMWNqbHFvRmZ1aU1qQ0ZJL3Bxb2gwZHYzTXJJVlI5WFVpK2NV
    dU5mZThReHVvZTc2RGp3UkUKZzVxbGVOYm1zYmhRMy9kMjhxaWFDQVZINW5rU2pBblJTMy
    tZeUFxWDlIcXBwQlZjL3Y3elE0anRuSzRCYjF4bAplQkNDR2paUnRFVjZtODAyTG5TVjJz
    YjFqNW1KL3lVZEFnTUJBQUV3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCCkFKbFRiWllwNF
    d6TTNiUTN5WE4zbkJsVUNLcHNtb1ZobUdadnhTSDEwZENxQlc3OWd2VzQ5MTJ5d0t4T2k1
    QzkKSjhIT2RoOGNXUy93YmZhMGpQS1JZa0NRamcrK1ZqTk5USTZKdkpxSGZrSTczdXVxUm
    t3M3phWXhtSmplWWg1RQpNc2N5L3ZRdTlHVDNoZTZxTnQ2ajJNa3hqdENsY2YzbU9UdEov
    RTR4cm9QYUVrUjgydkFUSnZIdEZJZHl3WUhkCldka1VGeEI3MlVKKzB6bU1yMExTZ0VBY2
    FrZG9VNDNYUXYrajJaR0VaeWtsbDNQY0tGRFRXOWJjb0R3aSswd0EKK1VhcU1WZmhNaHA4
    eVF3NXhzc3hxc24rYXFkRmE1OSsvVXNuU0VzYUErL1JKZVd1UzA0UVo3MU9GTHprNWg4UQ
    o1WGpOai93Nm5heHByamhUOHdWNndTZXB4Qi9CRklyMDBZbGEyM1VxVGRjL1hJdE5Hcldt
    M25QQUt6NDVhRmYzCmhsZEF2aERQS3Z3UWx4bXdhMktndWlQcXpNb2Y5dHpjeW5uOG80Nl
    BqL3BWTzFYZURLNEhpRXBjb01aU0JtM0UKR0xIOW9NbkZrbXRTaGsrTXpYUlV1cnBZV2Q0
    MjhHR0I4U1M0MHlYTTJHcXhEWDZmZ2pIZVQ5S0VuT2FpMSszRwpyOWVlbEp1VWNnZU9NdX
    hoZit3QVNKaU9OWFpHS3R4NTVZcHgwN2h0Sll4SUFOeXhpZHNxWjlWdlhYTjkxSCtFCkcx
    aUx6ODc2RXpKTTd2S0NHa2VqVCs0MnFUaFZ6Q2VOanI2d3NISGd1S0hUVnJkSHdhMXBGZ2
    tuUGR2T3dOcVIKYW16cHVmUTlXTkVPalhrcmZxQ3k0RTYvSVFhOThwb2ZuU3hIa3FCQWYy
    dmwKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQk
    FRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQzVoQWNjNk1WTVNIYm0KdDZ4NUc0R1dmcVE4
    OUU5VzNPYVd3QjdEZ3loL1ZCWmsxN1Y1amhWZ2x0UlE4Tk1PNUk0SzFkNHVOQUsxdkRERw
    pyUURDcHFWdTk4R1JBanZJbmNQeFJRZ2JhMHFtdWtyNEJDMUlEU0FIZVpmR2xwMko1azJF
    SHZ5L1owNFNOOE04CmZqVG81S1Z2TTJlWWl4L3FNWm1IemRRUFcrMWFyTkdIVzdHK3hiY2
    lsWlE4cGVnY1FMK3liaWhZU0dnN290RWoKVGFjeHVXTnl6U0VkV2tkTHZyQTB6UDhBZnlu
    Zi9UM2VDcUl2bXVSOWNsSTR6T0p4dmZPUVFYREE4cGdacjdSMwp6RWZucXZOYjVzVGdIcn
    ovTFd3d1RmenBiUzArTHBDN1ZrWkN1MnpUTUZGZkpFZ3V6cW5qTkhvZERIUUhPRkgrCjFj
    ME9adXE4MTRWZmQzSDZXUWZsUTM1eGxVSFBzNVQzV3dwcUkvdVlCdEJBTkRqWlQ3Wk5SZE
    lMWDFBSUdnZjEKQ1FUeTJpdkwwYUxHLzE2Vm1kMnNZSWdZUFAwY3A3cjJTNFRhdWxuRmhT
    NmtYN3JrYkJNUVBZOFB2MWNNQ2I3egp1NVJJYkJwdEYwUVREVlhkUlBtczVYOEk0ZWtOVl
    huN3JLakhLa1RnMnIrQ1RSOVgxeFlFRDBKTkZVc0RyTWNYCkZmTHJYSnF2dFhJNWFxQlg3
    b2pJd2hTUDZhcUlkSGI5ekt5RlVmVjFJdm5GTGpYM3ZFTWJxSHUrZzQ4RVJJT2EKcFhqVz
    VyRzRVTi8zZHZLb21nZ0ZSK1o1RW93SjBVdC9tTWdLbC9SNnFhUVZYUDcrODBPSTdaeXVB
    VzljWlhnUQpnaG8yVWJSRmVwdk5OaTUwbGRyRzlZK1ppZjhsSFFJREFRQUJBb0lDQUNtan
    ZzejRXa0NUQzAwaDhPNkdCQUk1CmpyZTN4bzhpcWdjd1BEZDZHdjdwYXRWYnJYb0pNRGNy
    NDUvL1RnQkx3SzRoN3VyRDljL0EyOW5jUHcxeHhqUXcKSEJ4bU9mRC9xRmxoT3o2Y1NIYy
    8zVS9wOEJmNkNqUmpVSFBjbnFPek03YnlGWjBJblBkdDJMNmRQVmNBNnprWQplcW84bi84
    Ni90RUNuQlNPZDZvZ25DOGJuN3ZJT1NEa0hnKzIxWEJ5QUJVV3NLdVFKUVV0dUcrS0lIc0
    N0NVd2CkFUM0xZN0ZXcmNwTU1QaDFrbnFhSnViTjBEV0xPTG9IalBqKzA5emYyK21ISnIz
    SU5lZWVEbzNOSmw2VGVtZ28KVmd4UUdlL1V6REhUYjI4ZGVFZzZ2M1d0R2J3a3dYcHRuL1
    lRK0xxNDNGMEpERmUwMGQ1RS8vS0pIcXVhNGhqNgpuL1d0YVpnT2grZm1vK1djYlJHS3Vs
    UTR6YURQRzdGMEp4K3czUUM3d0Q3OTFWY1grWkN0VG80QmF1ZnpIS3J3CmRoNGl4eHBoNy
    s2WDIzdnRwc281UEhQRmFJa0ZTRVYxM1FSQjBIdElNSXRiMnRrTmhVakowYjJpcDl2RkV0
    TXoKRldqeU5SbkdtNm5PWGhCR3RsWkVoc1JJS211NGNld3FHUFN0dWRxRHc4YjExcHFjcW
    hNam1iN3ZvWk96YXhkUwpQY1B3SWtTVklZOHYvdUYvTTBwbHhJN211RkptaFlCR2FnaVdv
    NHFVZVhlQkxacHpQTkVOS2o5ZE5jeHhpcTFzCkRBUGxSYkw3RlNuNHZwYktwWlEzM3N5a0
    Vya0tDRHhOK0tqSGpGQ29NN0h4eTBNL083RzNtRDlLUC9GME8xZzYKNGxaeUNrV2FrN3k3
    UmYrUHNQQ3BBb0lCQVFEd2xFSnhHY0xUVm54SGZhOVA5amo0OVREZ2wxdFU3VWFxOEQzUw
    pWeGxHaTZ6UXF3K1RVbnkxb0M3ZCt0RFY5bHUybFJtZlpNa01hTDBVM044K3dzdjU0Y1J3
    eWprUkZnRUNFRk1XCm9vTTEzYjhXQURRTzZmbllsb3p5TWIzdk52eExLSVJRSzlNT2RQUz
    VheGNqL2lUKzZTYkhZbEJPL2ZHclRodVkKTnNzNWhRbGE1Vng2Z0FPRVhHM0ZPWnpRbDVi
    WXQwaC94UWkyYmxGTUdFVGFNOURmS0F4TDVJVE1MWHJVZ3ZSYwpvZkJ2aW8wNFJBeXBMYj
    dONGFLWXJFNGNXa2R0WGhJNEZSd1hvZDFYN3dSZ2hIQW1ZSTlDNzZjNzd4VjZYajJuCkxC
    RWhvS3ZTaW9QcE54Z3Y0NXR6c0RQVStmSG9pZG02Nk5YaW1vSTBoenVkbmVVZkFvSUJBUU
    RGYURjU0h5MjkKVUdYRjBDbzdPWFNOaEhoK0cxRnFTSGdpdjNmYWl3VWM5RWdEZUNLNDNz
    eWFuTEVLaktyVzZrRnBMTkdGNUozYgorV1hyUVJFNWZZYzRWS3Q0U3FiOVhuTjdHc3pNYU
    FnOE81Y0ozVjJDbEpJZTRCVm5HZExEbzZMUXd0WCtkYjVvCjltT3laY002S2s2NUhucWdj
    M2lESG5xVmdwM2x4R0dpNitGeEgveDhmK1JqWFBBNS9JZUI1NDF3bzAzMHpzUkkKZGJrYy
    9CZmI1dWVZOGtjSTJqaVVyaEZyV1JMZWhoNmVub1dOTVI5eGZKYlhPM1NQdUVoNjNBQlFD
    d2g3WGFHbwpjSlJjUmlCRXpSeFhCRmFtaVloWWFmSFZTQ2xjczJ6OThEeEdZanhLSm4rcn
    RvUmxyODBwTnJkSldaZ1M0Q0dPCms2UStxNm5PY0JKREFvSUJBRVZmV3pGbDdrb212RHVa
    UUg1Y1Q5MXFScWZjdlZkbC9HUzZWZmxiYUV4eFptbmQKaWVZL2VQcWVzQ1VPZUQzYWhtUE
    Y1dGVScG0vUG5BWnlFbVgwb2dEeVcwVHk2elhFRkpKVnhyL1dLT1BWaDQ1KwpqSVJvYjhW
    RzFHbmFjaHlTekhtWHUxK3E0M2Rkdmx2aFI1RDNiZytiaDdVaTRtbUV6TFZMRnFYejF2Sk
    ZMSWRyCmNCbGE1S2k4Um1NQzAvZEtYeE1xOXRyeEpDd0c3Nlp6c1JjQ3JnNUxiQkJPV3dU
    TmNJZnJJeSs2K3F3UFZkMk4Kc2VEdThnQklPaXl3TXUzMkVuYTFFNmZjWG5kcUUzdVJ6cj
    lPTVZDL3MwL243MTlXOStpTFdGZm1XeUpKUklLMwpzb1lEZnhRQUhBbG1HK3drRHQreE1I
    bTNQa1hUckF3ZG10RStnSjBDZ2dFQUU1MTNXMldkdGVIM091Q2tVWjR6CjVwdnpIUlM1MG
    tYQktqSzhSZ3JxUnlZK3dabCtXY0JKdEZNOWhEN1YrdVRyK3ZkcEdsVE5HcjU5VWhMMUV6
    RlYKN2xMN2RzaDBMMWpqUUtnNUVWYUUrdmN3MnRvVUlKV0NyMjYwc2JudkoyRnJIRE0vOE
    RqaTRxc1kzUEVmcFBmdgpPcFc4dVpTL3RNZWlocGlqOStDN2t1UzlVZkJMdGxNKzdtQ2R2
    aVZKa2E3Z2J3RExEamc5YUxYSjN3ZHRsM3dxCkp4aHIxb1ZZZWUyUjdZaThSMEFzYXJaMX
    JzSGl6ZlFEU1ArdlpWaDZXenJoRFJNTGxMYUpDYU9tR2tVZGo3aVIKeUZPMkNIWkNCZ2NB
    OEtCcSs3c1lhV01sbWhqSXhOVnVlakY0bG1JUmtMYlBINHEzZ2FpanJQY2VxdHVEMCs5dQ
    o0UUtDQVFFQXdkM3M5bHZ1SkdLTksxazN4dTR5K2QyV2xldWRPRTJKN1Vpd0V5Y2RZejFR
    UzVRQnhXdVJtYm1PCmRGQmpzc2VXZVA5T1MwcWkrZWZRKzRSSDNGWkRGTFIxY0JLeU9XZV
    dqUS9BeGdVbG5aZHdMSlhzOEFlcEtWMmEKcTA0Ym84Z2M1VVl4VFV3SSt3SXdmTmI0NmY1
    WXNtNXRtUTNSNTcxbzdwVmpINEtHWVNxUUdvOEF6L0JPYU40Sgprd0lhWTJGSU5GUEZBdn
    lXc3ArYWl6RUtNMTdpSnpUeGhTczdWUy80Um9KcmRabS9GT1pWcW9Tb2gvclNZZFBMCjhD
    akpuS3JNT2EyT1BEdmkrMDRwRVhWc0VmRnlOblp3Q2RveTZOd002Z2svNFlVcDE4SzB3R0
    NjbGFZR1ZoYzIKeCtvUTd1M04zM3draEE3YVIzZmltUDlrME9oaVNnPT0KLS0tLS1FTkQg
    UFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: npm-server-certs
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: azure-npm
    component: controller
  name: azure-npm
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9001
    targetPort: 10092
  selector:
    component: controller
    k8s-app: azure-npm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: azure-npm
    component: controller
  name: npm-controller-metrics-cluster-service
  namespace: kube-system
spec:
  ports:
  - name: metrics
    port: 9000
    targetPort: 10091
  selector:
    component: controller
    k8s-app: azure-npm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    app: azure-npm
    component: controller
  name: azure-npm-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: controller
      k8s-app: azure-npm
  template:
    metadata:
      annotations:
        azure.npm/scrapeable: ""
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: controller
        k8s-app: azure-npm
    spec:
      containers:
      - args:
        - start
        - controlplane
        command:
        - azure-npm
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NPM_CONFIG
          value: /etc/azure-npm/azure-npm.json
        image: azure-npm:v1.4.1
        name: azure-npm
        ports:
        - containerPort: 10091
          name: metrics
        - containerPort: 10092
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 300Mi
          requests:
            cpu: 250m
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/azure-npm/certs
          name: certs
        - mountPath: /var/log
          name: log
        - mountPath: /etc/protocols
          name: protocols
        - mountPath: /etc/azure-npm
          name: azure-npm-config
      priorityClassName: system-node-critical
      serviceAccountName: azure-npm
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: certs
        projected:
          sources:
          - secret:
              name: npm-server-certs
          - secret:
              name: npm-ca-certs
      - hostPath:
          path: /var/log
          type: Directory
        name: log
      - hostPath:
          path: /etc/protocols
          type: File
        name: protocols
      - configMap:
          name: azure-npm-config
        name: azure-npm-config
