apiVersion: v1
kind: Service
metadata:
  name: npm-daemon-metrics-cluster-service
  namespace: kube-system
  labels:
    app: azure-npm
    component: daemon
spec:
  selector:
    k8s-app: azure-npm
    component: daemon
  ports:
  - name: metrics 
    port: 9000
    targetPort: 10091
