apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-cni-manager-master
spec:
  selector:
    matchLabels:
      acn: cni-installer
  template:
    metadata:
      labels:
        acn: cni-installer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      hostNetwork: true
      containers:
        - name: azure-cni-installer
          image: mcr.microsoft.com/containernetworking/azure-cni-manager:v1.1.8-4-g4d14734-dirty-3
          imagePullPolicy: Always
          env:
            - name: CNI_OS
              value: linux
            - name: CNI_TYPE
              value: singletenancy
            - name: CNI_MODE
              value: transparent
            - name: CNI_IPAM_TYPE
              value: azure-cns
            - name: CNI_EXCEMPT_BINS
              value: azure-vnet-telemetry,azure-vnet-telemetry.config
          securityContext:
            privileged: true
          volumeMounts:
            - name: cni-bin
              mountPath: /opt/cni/bin
            - name: cni-conflist
              mountPath: /etc/cni/net.d
            - name: cni-datapath-log
              mountPath: /var/log/azure-vnet.log
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
            type: Directory
        - name: cni-datapath-log
          hostPath:
            path: /var/log/azure-vnet.log
            type: File
        - name: cni-conflist
          hostPath:
            path: /etc/cni/net.d
            type: Directory
