parameters:
  name: ""
  displayName: ""
  pipelineBuildImage: "$(BUILD_IMAGE)"

stages:
  - stage: ${{ parameters.name }}
    displayName: E2E - ${{ parameters.displayName }}
    dependsOn: 
     - setup
     - build_and_test
    jobs:
      - job: ${{ parameters.name }}
        displayName: Singletenancy AKS Swift Suite - (${{ parameters.name }})
        timeoutInMinutes: 120
        pool:
          name: "$(BUILD_POOL_NAME_SWIFT)"
          demands: 
          - agent.os -equals Linux
          - Role -equals $(CUSTOM_E2E_ROLE)
        variables:
          GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
          GOBIN: "$(GOPATH)/bin" # Go binaries path
          Tag: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.Tag'] ]
          modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"
        steps:
          - template: e2e-step-template.yaml
            parameters:
              name: ${{ parameters.name }}
