parameters:
  dependsOn: ""
  name: ""

stages:
  - stage: experimental
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn: ${{ parameters.dependsOn }}
    displayName: "Experimental multitenancy"
    jobs:
      - job: test_multitenancy
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              echo "experimental stage"
              go version
              az account show
              make -C ./hack/aks connect-multitenancy
              cd ~/.kube/
              pwd
              ls
            name: "test"
            displayName: "Test Multitenancy"