parameters:
  dependsOn: ""
  name: ""

stages:
  - stage: experimental
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn: ${{ parameters.dependsOn }}
    displayName: "Experimental multitenancy"
    jobs:
      - job: connect cluster
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              echo "experimental stage"
              go version
              cd ~/.kube/
              pwd
              ls
            name: "test_prereqs"
            displayName: "Test Multitenancy Prereqs"
          - template: connect-cluster-template.yaml
            parameters:
              group: $(GROUP)
              cluster: $(CLUSTER)
      - job: prepare_cns
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
          steps:
          - script: |
              make cns-image-name-and-tag
              make cns-image
              make cns-image-name-and-tag
      - job: test_multitenancy
          - script: |
              make test-multitenancy
            name: "test"
            displayName: "Test Multitenancy"
