parameters:
  dependsOn: ""
  name: ""

stages:
  - stage: experimental
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn: ${{ parameters.dependsOn }}
    displayName: "Experimental multitenancy"
    jobs:
      - job: connect_cluster
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              echo "experimental stage"
              go version
              cd ~/.kube/
              pwd
              ls
            name: "test_prereqs"
            displayName: "Test Multitenancy Prereqs"
          - template: connect-cluster-template.yaml
            parameters:
              group: $(GROUP)
              cluster: $(CLUSTER)
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                make cns-image-name-and-tag
                make cns-image
            name: "make_cns"
            displayName: "Make cns image and tag while logged in"
          - script: |
              make cns-image-name-and-tag
              make cns-image
            name: "make_cns"
            displayName: "Make CNS Image"
          - script: |
              make test-multitenancy
            name: "test"
            displayName: "Test Multitenancy"
