pr: none
trigger: none

variables:
- group: ACN-CNI-Pipeline

stages:
  - stage: setup
    displayName: Variable Group POC
    jobs:
      - job: vgroup
        displayName: View Variable Group
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az pipelines variable-group show --id $(CNI_VAR_GROUP) --org $(System.TeamFoundationCollectionUri) --project $(System.TeamProject) --debug

            displayName: "Configure Defaults and List"
            condition: always()
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

          - bash: |
              az pipelines variable-group variable update --id $(CNI_VAR_GROUP) --org $(System.TeamFoundationCollectionUri) --project $(System.TeamProject) --name CILIUM_IMAGE_REGISTRY --value "Changed it was"
            displayName: "Change Variable"
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

          - bash: |
              az pipelines variable-group show --id $(CNI_VAR_GROUP) --org $(System.TeamFoundationCollectionUri) --project $(System.TeamProject) --debug
            displayName: "List Variable Group"
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)


  - stage: init
    displayName: "Build and Push Cilium Image"
    jobs:
      - job: build_and_push_cilium_image
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
        steps:
          - bash: |
              echo hi
            name: BuildCiliumImage
            displayName: "Build Cilium Image"
