pr: none
trigger: none

stages:
  - stage: setup
    displayName: Variable Group POC
    jobs:
      - job: vgroup
        displayName: View Variable Group
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - bash: |
              echo $(System.TeamFoundationCollectionUri)
              echo $(System.TeamProject)
            name: BuildCiliumImage
            displayName: "Build Cilium Image"

          - bash: |
              az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)'
              az devops configure --list
            displayName: 'Set default Azure DevOps organization and project'

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az devops configure --list
                az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)'
                az devops configure --list
                az pipelines variable-group show --id $(CNI_VAR_GROUP) --debug

            displayName: "Restart Nodes"
            condition: always()
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)


  - stage: init
    displayName: "Build and Push Cilium Image"
    jobs:
      - job: build_and_push_cilium_image
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
        steps:
          - bash: |
              echo hi
            name: BuildCiliumImage
            displayName: "Build Cilium Image"
