parameters:
  - name: dependsOn
    type: string
    default: ""
  - name: name
    type: string
    default: cilium_nodesubnet_e2e
  - name: displayName
    type: string
    default: ""
  - name: clusterType
    type: string
    default: nodesubnet-byocni-nokubeproxy-up
  - name: clusterName
    type: string
    default: cilndsubnete2e
  - name: vmSize
    type: string
    default: ""
  - name: os
    type: string
    default: linux
  - name: arch
    type: string
    default: ""
  - name: osSKU
    type: string
    default: Ubuntu
  - name: hubbleEnabled
    type: boolean
    default: false
  - name: dualstackVersion
    type: string
    default: ""
  - name: cni
    type: string
    default: cilium
  - name: skip
    type: boolean
    default: false

stages:
  - stage: ${{ parameters.clusterName }}
    displayName: Create Cluster - ${{ parameters.displayName }}
    condition: eq('${{ parameters.skip }}', false)
    dependsOn:
      - ${{ parameters.dependsOn }}
      - setup
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
    jobs:
      - template: ../../templates/create-cluster.yaml
        parameters:
          name: ${{ parameters.name }}
          displayName: ${{ parameters.displayName }}
          clusterType: ${{ parameters.clusterType }}
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          vmSize: ${{ parameters.vmSize }}
          region: $(REGION_AKS_CLUSTER_TEST)

  - stage: ${{ parameters.name }}
    displayName: E2E - ${{ parameters.displayName }}
    condition: and(succeeded(), eq(variables.TAG, variables.CURRENT_VERSION), eq('${{ parameters.skip }}', false))
    variables:
      TAG: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.Tag'] ]
      CURRENT_VERSION: $[ stagedependencies.containerize.check_tag.outputs['CurrentTagManifests.currentTagManifests'] ]
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
      GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
      GOBIN: "$(GOPATH)/bin" # Go binaries path
      modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"
    dependsOn:
    - setup
    - publish
    - ${{ parameters.clusterName }}
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    jobs:
      - job: ${{ parameters.name }}
        displayName: Nodesubnet with Cilium - (${{ parameters.name }})
        timeoutInMinutes: 120
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands:
          - agent.os -equals Linux
          - Role -equals $(CUSTOM_E2E_ROLE)
        steps:
          - template: cilium-nodesubnet-e2e-step-template.yaml
            parameters:
              name: ${{ parameters.name }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              arch: ${{ parameters.arch }}
              os: ${{ parameters.os }}
              scaleup: ${{ parameters.scaleup }}

      - template: ../../cni/k8s-e2e/k8s-e2e-job-template.yaml
        parameters:
          sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          os: ${{ parameters.os }}
          datapath: true
          dns: true
          cni: cilium
          portforward: true
          service: true
          dependsOn: ${{ parameters.name }}

      - job: failedE2ELogs
        displayName: "Failure Logs"
        dependsOn:
          - ${{ parameters.name }}
          - cni_${{ parameters.os }}
        condition: failed()
        steps:
          - template: ../../templates/log-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              cni: cilium

  - stage: delete_${{ parameters.clusterName }}
    displayName: Delete Cluster - ${{ parameters.displayName }}
    condition: and(always(), eq('${{ parameters.skip }}', false))
    dependsOn:
      - ${{ parameters.name }}
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    jobs:
      - job: delete
        displayName: Delete Cluster
        steps:
          - template: ../../templates/delete-cluster.yaml
            parameters:
              name: ${{ parameters.name }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              region: $(REGION_AKS_CLUSTER_TEST)
              sub: $(SUB_AZURE_NETWORK_AGENT_BUILD_VALIDATIONS)
              svcConn: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
