parameters:
  depend: ""
  clusterName: "" # unique identifier
  vmSize: ""
  retryCount: 5

jobs:
- job: windows_nodepool
  displayName: Add Windows Nodepool
  dependsOn: ${{ parameters.depend }}
  pool:
    name: $(BUILD_POOL_NAME_DEFAULT)
    demands:
    - agent.os -equals Linux
    - Role -equals $(CUSTOM_E2E_ROLE)
  steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
        scriptLocation: "inlineScript"
        scriptType: "bash"
        addSpnToEnvironment: true
        inlineScript: |
          set -e
          
          windows_nodepool=$(az aks nodepool list \
          --resource-group ${{ parameters.clusterName }} \
          --cluster-name ${{ parameters.clusterName }} \
          --query "[?osType=='Windows']" \
          --output tsv)

          if [ -z "$windows_nodepool" ]; then
            echo "No Windows node pool found in the AKS cluster."
          
            make -C ./hack/aks set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}
            make -C ./hack/aks windows-nodepool-up AZCLI=az SUB=$(SUB_AZURE_NETWORK_AGENT_BUILD_VALIDATIONS) CLUSTER=${{ parameters.clusterName }} VM_SIZE_WIN=${{ parameters.vmSize }}
            echo "Windows node was successfully added to v4 Overlay Cluster"
            kubectl cluster-info
            kubectl get node -owide
            kubectl get po -owide -A
          else
            echo "Windows node pool already exists in the AKS cluster."
          fi
      name: "Add_Windows_Node"
      displayName: "Add windows node on v4 overlay cluster"
      retryCountOnTaskFailure: ${{ parameters.retryCount }}
