parameters:
  depend: ""
  clusterName: "" # unique identifier
  vmSize: ""

jobs:
- job: windows_nodepool
  displayName: Add Windows Nodepool
  dependsOn: ${{ parameters.depend }}
  pool:
    isCustom: true
    type: linux
    name: $(BUILD_POOL_NAME_DEFAULT)
    demands:
    - agent.os -equals Linux
    - Role -equals $(CUSTOM_E2E_ROLE)
  timeoutInMinutes: 30
  steps:
    - checkout: azure-container-networking
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
        scriptLocation: "inlineScript"
        scriptType: "bash"
        addSpnToEnvironment: true
        inlineScript: |
          set -e
          
          windows_nodepool=$(az aks nodepool list \
          --resource-group ${{ parameters.clusterName }} \
          --cluster-name ${{ parameters.clusterName }} \
          --query "[?osType=='Windows']" \
          --output tsv)

          if [ -z "$windows_nodepool" ]; then
            echo "No Windows node pool found in the AKS cluster."

            # wait for cluster to update
            while true; do
              cluster_state=$(az aks show \
              --name "${{ parameters.clusterName }}" \
              --resource-group "${{ parameters.clusterName }}" \
              --query provisioningState)
              
              if echo "$cluster_state" | grep -q "Updating"; then
                echo "Cluster is updating. Sleeping for 30 seconds..."
                sleep 30
              else
                break
              fi
            done
            # cluster state is always set and visible outside the loop
            echo "Cluster state is: $cluster_state"

            make -C ./hack/aks set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}
            make -C ./hack/aks windows-nodepool-up AZCLI=az SUB=$(SUB_AZURE_NETWORK_AGENT_BUILD_VALIDATIONS) CLUSTER=${{ parameters.clusterName }} VM_SIZE_WIN=${{ parameters.vmSize }}
            echo "Windows node was successfully added"
            kubectl cluster-info
            kubectl get node -owide
            kubectl get po -owide -A
          else
            echo "Windows node pool already exists in the AKS cluster."
          fi
      name: "Add_Windows_Node"
      displayName: "Add windows node to cluster"
      retryCountOnTaskFailure: 5
