jobs:
- job: build
  displayName: Build Binaries
  pool:
    type: linux
  variables:
    LinuxContainerImage: $(LinuxContainerImage2)

    ob_outputDirectory: $(Build.ArtifactStagingDirectory)/output
    ob_git_checkout: true
  steps:
  - checkout: azure-container-networking

  - bash: |
      make ipv6-hp-bpf-lib
      make all-binaries-platforms
    displayName: "Build all platform binaries"
    workingDirectory: $(ACN_DIR)

  - script: |
      mkdir -p ./output/bins
      cd ./output
      find . -name '*.tgz' -print -exec mv -t ./bins/ {} +
      find . -name '*.zip' -print -exec mv -t ./bins/ {} +
      shopt -s extglob
      rm -rf !("bins")
    displayName: "Prepare Artifacts"
    workingDirectory: $(ACN_DIR)

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(ACN_DIR)/output"
      targetFolder: $(Build.ArtifactStagingDirectory)/output
