jobs:
- job: build
  displayName: Build Binaries
  pool:
    type: linux
  variables:
    LinuxBuildContainer: $(LinuxBuildContainer2)

    ob_outputDirectory: $(Build.ArtifactStagingDirectory)/output
      #ob_git_checkout: true
  steps:
  - checkout: azure-container-networking

  - task: GoTool@0
    inputs:
      version: '$(GOVERSION)'

  - bash: |
      go install github.com/jstemmer/go-junit-report/v2@latest
    displayName: "Install Dependencies"

  - bash: |
      make ipv6-hp-bpf-lib
      make all-binaries-platforms
    displayName: "Build all platform binaries"

  - script: |
      mkdir -p ./output/bins
      cd ./output
      find . -name '*.tgz' -print -exec mv -t ./bins/ {} +
      find . -name '*.zip' -print -exec mv -t ./bins/ {} +
      shopt -s extglob
      rm -rf !("bins")
    displayName: "Prepare Artifacts"

  - task: CopyFiles@2
    inputs:
      sourceFolder: "output"
      targetFolder: $(Build.ArtifactStagingDirectory)/output
