parameters:
  os: linux
  continueOnError: true

jobs:
  - job: ${{ parameters.name }}
    displayName: Cluster - ${{ parameters.name }}
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(ACN_TEST_SERVICE_CONNECTION)
          scriptLocation: "inlineScript"
          scriptType: "bash"
          addSpnToEnvironment: true
          inlineScript: |
            set -e
            echo "Check az version"
            az version
            if ${{ lower(contains(parameters.clusterType, 'dualstack')) }}
            then
              echo "Install az cli extension preview"
              az extension add --name aks-preview
              az extension update --name aks-preview
            fi

            bash .pipelines/multitenancy/scripts/setup-mt-cluster.sh \
              --mt-test-cluster "${{ parameters.clusterName}}" \
              --scenario ${{ parameters.scenario }}

            echo "Cluster successfully created"
        displayName: Cluster - ${{ parameters.clusterType }}
        continueOnError: ${{ parameters.continueOnError }}
