parameters:
  name: ""
  displayName: ""
  clusterType: ""
  clusterName: "" # Recommended to pass in unique identifier
  vmSize: ""
  vmSizeWin: ""
  k8sVersion: ""
  osSkuWin: "Windows2022" # Currently we only support Windows2022
  dependsOn: ""
  region: ""
  os: linux

jobs:
  - job: ${{ parameters.name }}
    displayName: Cluster - ${{ parameters.name }}
    steps:
      - bash: |
          set -e

          echo "Check az version"
          az version

          echo "Install az cli extension preview"
          az extension add --name aks-preview
          az extension update --name aks-preview
        displayName: "Install AzCLI Extentions"
        condition: and(succeeded(), ${{ contains(parameters.clusterType, 'dualstack') }})
 
      - task: AzureCLI@2
        displayName: Cluster - ${{ parameters.clusterType }}
        continueOnError: contains(parameters.clusterType, 'dualstack')
        env:
          AZCLI: az
          REGION: ${{ parameters.region }}
          CLUSTER: ${{ parameters.clusterName }}
          CLUSTER_TYPE: ${{ parameters.clusterType }}
          SUB: $(SUB_AZURE_NETWORK_AGENT_BUILD_VALIDATIONS)
          VM_SIZE: ${{ parameters.vmSize }}
          VM_SIZE_WIN: ${{ parameters.vmSizeWin }}
          OS: ${{ parameters.os }}
          OS_SKU_WIN: ${{ parameters.osSkuWin }}
        inputs:
          azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
          scriptLocation: "inlineScript"
          scriptType: "bash"
          addSpnToEnvironment: true
          inlineScript: |
            set -e

            mkdir -p ~/.kube/
            make -C ./hack/aks azcfg

            make -C ./hack/aks "$CLUSTER_TYPE"
            #WINDOWS_USERNAME=${WINDOWS_USERNAME} WINDOWS_PASSWORD=${WINDOWS_PASSWORD}

            echo "Cluster successfully created"
