parameters:
  os: linux
  continueOnError: true

jobs:
  - job: ${{ parameters.name }}
    displayName: Cluster - ${{ parameters.name }}
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(ACN_TEST_SERVICE_CONNECTION)
          scriptLocation: "inlineScript"
          scriptType: "bash"
          addSpnToEnvironment: true
          inlineScript: |
            set -ex
            echo "Check az version"
            az version
            if ${{ lower(contains(parameters.clusterType, 'dualstack')) }}
            then
              echo "Install az cli extension preview"
              az extension add --name aks-preview
              az extension update --name aks-preview
            fi

            source ./.pipelines/multitenancy/scripts/utils.sh
            export_envVars ${{ parameters.scenario }} 
            mkdir -p ~/.kube/
            make -C ./hack/aks azcfg AZCLI=az REGION=${LOCATION}

            make -C ./hack/aks ${{ parameters.clusterType }} \
            AZCLI=az REGION=$LOCATION SUB=$(ACN_TEST_SERVICE_CONNECTION) \
            CLUSTER=${{ parameters.clusterName }} \
            VM_SIZE=$VM_SIZE \
            GROUP=$RG

            echo "Cluster successfully created"
        displayName: Cluster - ${{ parameters.clusterType }}
        continueOnError: ${{ parameters.continueOnError }}
