stages:
  - stage: test
    displayName: Test ACN
    dependsOn:
      - setup
    jobs:
      - job: test
        displayName: Run Tests
        variables:
          STORAGE_ID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.StorageID'] ]
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              set -e
              make tools

              # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml),
              # stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code.
              # Read all output from fd 4 (output from tee) and write to top stdout
              { { { {
                    sudo -E env "PATH=$PATH" make test-all;
                    echo $? >&3;
                    } | tee >(build/tools/bin/go-junit-report > report.xml) >&4;
                  } 3>&1;
                } | { read xs; exit $xs; }
              } 4>&1
            retryCountOnTaskFailure: 3
            name: "Test"
            displayName: "Run Tests"
          - bash: |
              sudo ln -s $(pwd)/build/tools/bin/gocov /usr/local/bin/gocov
              sudo ln -s $(pwd)/build/tools/bin/gocov-xml /usr/local/bin/gocov-xml
              gocov convert coverage-all.out > total_ut_coverage.json
              gocov-xml < total_ut_coverage.json > total_ut_coverage.xml
            name: "Coverage"
            displayName: "Generate Coverage Report"
            condition: always()
          - task: PublishCodeCoverageResults@2
            displayName: "Publish Code Coverage Report"
            condition: always()
            inputs:
              summaryFileLocation: total_ut_coverage.xml
          - task: BuildQualityChecks@8
            displayName: "Check Code Coverage Regression"
            condition: always()
            inputs:
              checkCoverage: true
              coverageFailOption: "build"
              coverageType: "lines"
              fallbackOnPRTargetBranch: false
              baseBranchRef: "master"
              allowCoverageVariance: true
              coverageVariance: 0.25

  - stage: test_windows
    displayName: Test ACN Windows
    dependsOn:
      - setup
    jobs:
      - job: test
        displayName: Run Tests
        variables:
          STORAGE_ID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.StorageID'] ]
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT_WINDOWS_ALT)"
        steps:
          # Only run one go test per script
          - script: |
              cd azure-container-networking/
              go test -timeout 30m ./npm/... ./cni/... ./platform/...
            retryCountOnTaskFailure: 3
            name: "TestWindows"
            displayName: "Run Windows Tests"
