jobs:
- job: env
  displayName: Provision Build Environment Variables
  variables:
    ACN_DIR: azure-container-networking
    ACN_PATH: $(System.DefaultWorkingDirectory)/$(ACN_DIR)
    ob_outputDirectory: $(Build.ArtifactStagingDirectory)
    ob_git_checkout: true
  pool:
    type: linux
  steps:
  - checkout: azure-container-networking
 
  - template: /cicd/pkg/toolsets/template.toolset.steps.yaml@self
    parameters:
      os: mariner
      install:
      - docker

  - script: |
      set -e
      # Configure Build Container
      ls -al
      BUILD_NUMBER="${BUILD_BUILDNUMBER//./-}"
      export CONTAINER_BUILDER=docker
      export CONTAINER_RUNTIME=docker
      export CONTAINER_TRANSPORT=docker
      COMMIT_ID=""$(make revision)"-"$(date "+%d%H%M")""
      VERSION_TAG="$(make version)"
      NPM_VERSION="$(make npm-version)"
      echo "##vso[task.setvariable variable=StorageID;isOutput=true]$BUILD_NUMBER"
      echo "##vso[task.setvariable variable=commitID;isOutput=true]$COMMIT_ID"
      echo "##vso[task.setvariable variable=Tag;isOutput=true]$VERSION_TAG"
      echo "##vso[task.setvariable variable=npmVersion;isOutput=true]$NPM_VERSION"

      echo >&2 "[group]System Details"
      cat /etc/os-release
      make --version
      uname -a
      sudo chown -R $(whoami):$(whoami) .
      echo >&2 "[endgroup]"
      echo >&2 "[group]Golang Environment"
      go version
      go env
      which go
      echo >&2 "[endgroup]"

      echo "$PATH"
      echo "------"
      echo "${BUILD_QUEUEDBY}"
      echo "${BUILD_REASON}" # manual, PR, IndividualCI
      echo "${BUILD_SOURCEBRANCH}"
      cp .pipelines/Dockerfile "$ARTIFACTS_DIR"

    name: EnvironmentalVariables
    displayName: "Set Build Output Variables"
    workingDirectory: $(ACN_DIR)
    env:
      ARTIFACTS_DIR: $(Build.ArtifactStagingDirectory)

    # The artifact upload is performed automatically.
    # Leaving something here for documentation.
    #
    #- task: PublishPipelineArtifact@1
    #  inputs:
    #    artifactName: drop_setup_env
    #    targetPath: "$(Build.ArtifactStagingDirectory)"
    #    publishLocation: 'pipeline'
