parameters:
- name: exec
  type: jobList
  default: []

jobs:
- ${{ each job in parameters.exec }}:
  - job: test_${{ job.templateContext.testGroup }}
    displayName: "Unit Tests - (${{ job.displayName }})"
    pool:
      type: linux
    variables:
      STORAGE_ID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.StorageID'] ]
      #ob_artifactSuffix: ${{ job.templateContext.Suffix }} # this is needed to not collide published artifact containers
      ACN_DIR: azure-container-networking
      ACN_PATH: $(Build.SourcesDirectory)/$(ACN_DIR)
      ob_outputDirectory: $(Build.ArtifactStagingDirectory)
      ob_git_checkout: true
    steps:
    - checkout: azure-container-networking
  
    - ${{ if eq(job.templateContext.testGroup, 'windows') }}:
      - script: |
          pushd "$ACN_PATH"
            cd npm/
            go test ./...
          popd
        retryCountOnTaskFailure: 3
        displayName: "Run ${{ job.displayName }} Tests"
  
  
    - ${{ elseif eq(job.templateContext.testGroup, 'ubuntu') }}:
      - bash: |
          set -e
          pushd "$ACN_PATH"
            make tools
            # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml), stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code. Read all output from fd 4 (output from tee) and write to top stdout
            { { { {
                  sudo -E env "PATH=$PATH" make test-all;
                  echo $? >&3;
                  } | tee >(build/tools/bin/go-junit-report > report.xml) >&4;
                } 3>&1;
              } | { read xs; exit $xs; }
            } 4>&1
          popd
        retryCountOnTaskFailure: 3
        displayName: "Run Unit Tests (Ubuntu)"
  
  
    - ${{ elseif eq(job.templateContext.testGroup, 'mariner') }}:
      - script: |
          set -e
          pushd "$ACN_PATH"
            make tools
            # run test, echo exit status code to fd 3, pipe output from test to tee, which splits output to stdout and go-junit-report (which converts test output to report.xml), stdout from tee is redirected to fd 4. Take output written to fd 3 (which is the exit code of test), redirect to stdout, pipe to read from stdout then exit with that status code. Read all output from fd 4 (output from tee) and write to top stdout
            { { { {
                  sudo -E env "PATH=$PATH" make test-all;
                  echo $? >&3;
                  } | tee >(build/tools/bin/go-junit-report > report.xml) >&4;
                } 3>&1;
              } | { read xs; exit $xs; }
            } 4>&1
          popd
        retryCountOnTaskFailure: 3
        displayName: "Run Unit Tests (Mariner)"
  

    - ${{ else }}:
      - bash: |
          set -e
          echo >&2 "##[error]Invalid test selection ("$TEST_GROUP")"
          exit 1
        displayName: "[Error] Invalid Unittest Template Selection"
