pr: none
trigger: none

stages:
  - stage: update_cilium_version
    displayName: "Update Cilium Version and Restart Nodes"
    jobs:
      - job: update_version
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                echo "Redeploy all cilium components and update cilium version. Redeploy all to catch all changes between versions"
                echo "deploy Cilium ConfigMap"
                kubectl apply -f cilium/configmap.yaml
                kubectl apply -f test/integration/manifests/cilium/cilium-config.yaml
                echo "install Cilium ${CILIUM_VERSION_TAG}"
                envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/daemonset.yaml | kubectl apply -f -
                envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/deployment.yaml | kubectl apply -f -
                kubectl apply -f test/integration/manifests/cilium/cilium-agent
                kubectl apply -f test/integration/manifests/cilium/cilium-operator
                vmss_name=$(az vmss list -g MC_${CLUSTER}_${CLUSTER}_$(LOCATION) --query "[].name" -o tsv)
                make -C ./hack/aks restart-vmss AZCLI=az CLUSTER=${CLUSTER} REGION=$(LOCATION) VMSS_NAME=$vmss_name
                kubectl get node 
                kubectl get pod -A
            name: "UpdateCiliumVersion"
            displayName: "Update Cilium Version"
  - stage: scale_up_cluster
    displayName: "Scale Up Cluster"
    jobs:
      - job: scale_up1000
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                set -ex
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                echo "Scaling to 1000 nodes"
                az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 1000
            # vmss_name=$(az vmss list -g MC_${CLUSTER}_${CLUSTER}_$(LOCATION) --query "[].name" -o tsv)
            # make -C ./hack/aks scale-vmss AZCLI=az CLUSTER=${CLUSTER} REGION=$(LOCATION) VMSS_NAME=$vmss_name NODE_COUNT=1000
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 100
            # echo "Scaling to 200 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 200
            # echo "Scaling to 300 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 300
            # echo "Scaling to 400 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 400
            # echo "Scaling to 500 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 500
            # echo "Scaling to 600 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 600
            # echo "Scaling to 700 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 700
            # echo "Scaling to 800 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 800
            # echo "Scaling to 900 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 900
            # echo "Scaling to 1000 nodes"
            # az aks nodepool scale --name nodepool1 --cluster-name ${{ parameters.clusterName }} --resource-group ${{ parameters.clusterName }} --node-count 1000
            name: "ScaleUp1000"
            displayName: "Scale up to 1000 Nodes"
            timeoutInMinutes: 0

      # - job: scale_up100
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 100
      #   timeoutInMinutes: 120
      # - job: scale_up200
      #   dependsOn: scale_up100
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 200
      #   timeoutInMinutes: 120
      # - job: scale_up300
      #   dependsOn: scale_up200
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 300
      #   timeoutInMinutes: 120
      # - job: scale_up400
      #   dependsOn: scale_up300
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 400
      #   timeoutInMinutes: 120
      # - job: scale_up500
      #   dependsOn: scale_up400
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 500
      #   timeoutInMinutes: 120
      # - job: scale_up600
      #   dependsOn: scale_up500
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 600
      #   timeoutInMinutes: 120
      # - job: scale_up700
      #   dependsOn: scale_up600
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 700
      #   timeoutInMinutes: 120
      # - job: scale_up800
      #   dependsOn: scale_up700
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 800
      #   timeoutInMinutes: 120
      # - job: scale_up900
      #   dependsOn: scale_up800
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 900
      #   timeoutInMinutes: 120
      # - job: scale_up1000
      #   dependsOn: scale_up900
      #   steps:
      #     - template: ../scale-test-templates/scale-cluster.yaml
      #       parameters:
      #         clusterName: "cilium-scale"
      #         nodeCount: 1000
      #   timeoutInMinutes: 120
  - stage: label_nodes
    displayName: "Label Nodes for Testing"
    jobs:
      - job: label_nodes
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Set node label scale-test=true and connectivity-test=true for testing"
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                cd test/scale 
                chmod +x label-nodes.sh
                ./label-nodes.sh
            name: "LabelNodes"
            displayName: "Label all Nodes"
  - stage: scale_cluster_deployments
    displayName: "Scale deploments for Network Policies Check"
    jobs:
      - job: scale_deployments
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "scale deployment and to prep for network policies test"
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                cd test/scale
                chmod +x test-scale.sh
                ./test-scale.sh --max-kwok-pods-per-node=0 --num-kwok-deployments=0 --num-kwok-replicas=0 --max-real-pods-per-node=200 --num-real-deployments=1 --num-real-replicas=80 --num-network-policies=2000 --num-unapplied-network-policies=2000 --num-unique-labels-per-pod=0 --num-unique-labels-per-deployment=5 --num-shared-labels-per-pod=3 --num-real-services=1 --delete-labels
            name: "scaling"
            displayName: "Run scale script"
  - stage: test_network_policies_connectivity
    displayName: "Test Network Policies"
    jobs:
      - job: network_policies
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Run network policies test"
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                cd test/scale/connectivity
                chmod +x test-connectivity.sh
                ./test-connectivity.sh --num-scale-pods-to-verify=40 --max-wait-for-initial-connectivity=600 --max-wait-after-adding-netpol=120
            name: "TestNetworkPolicies"
            displayName: "Network Policies Scale Test"
  - stage: scale_for_load_tests
    displayName: "Scale for load tests"
    jobs:
      - job: deploy_service
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                cd test/scale
                chmod +x test-scale.sh
                ./test-scale.sh --max-kwok-pods-per-node=0 --num-kwok-deployments=0 --num-kwok-replicas=0 --max-real-pods-per-node=200 --num-real-deployments=0 --num-real-replicas=60 --num-network-policies=0 --num-unapplied-network-policies=0 --num-unique-labels-per-pod=0 --num-unique-labels-per-deployment=5 --num-shared-labels-per-pod=3 --num-real-services=1 --delete-labels --num-real-nginx-deployments=1
            name: "TestLBServices"
            displayName: "Scale for load tests"
  - stage: benchmark_testing
    displayName: "Run apachebench test"
    jobs:
      - job: ap_test
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                echo "Deploy apachebench pod and run test"
                cd .pipelines/cni/scale-test-templates
                kubectl apply -f apache.yaml
                echo "wait for pod to become ready"
                sleep 5s
                kubectl get pod -owide
                AB_POD=$(kubectl get pod -l app=apachebench | grep apachebench | awk '{print $1}')
                kubectl exec -it $AB_POD -- ab -n 100000 -c 3 -r http://real-svc-00001.scale-test/
                echo "k top node"
                kubectl top node
                echo "k top pod"
                kubectl top pod
            name: "TestLBServices"
            displayName: "Apachebench testing"
  - stage: scale_down_cluster
    displayName: "Scale Down Cluster"
    jobs:
      - job: scale_down900
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 900
        timeoutInMinutes: 120
      - job: scale_down800
        dependsOn: scale_down900
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 800
        timeoutInMinutes: 120
      - job: scale_down700
        dependsOn: scale_down800
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 700
        timeoutInMinutes: 120
      - job: scale_down600
        dependsOn: scale_down700
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 600
        timeoutInMinutes: 120
      - job: scale_down500
        dependsOn: scale_down600
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 500
        timeoutInMinutes: 120
      - job: scale_down400
        dependsOn: scale_down500
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 400
        timeoutInMinutes: 120
      - job: scale_down300
        dependsOn: scale_down400
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 300
        timeoutInMinutes: 120
      - job: scale_down200
        dependsOn: scale_down300
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 200
        timeoutInMinutes: 120
      - job: scale_down100
        dependsOn: scale_down200
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 100
        timeoutInMinutes: 120
      - job: scale_down5
        dependsOn: scale_down100
        steps:
          - template: ../scale-test-templates/scale-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
              nodeCount: 5
        timeoutInMinutes: 120
  - stage: delete_test_namespaces
    displayName: "Delete Test Namespaces"
    jobs:
      - job: delete_namespaces
        steps:
        - task: AzureCLI@1
          inputs:
            azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
            scriptLocation: "inlineScript"
            scriptType: "bash"
            addSpnToEnvironment: true
            inlineScript: |
              echo "scale deployment and test network policies"
              az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
              kubectl delete ns scale-test
              kubectl delete ns connectivity-test
              kubectl get ns
          name: "DeleteTestNamespaces"
          displayName: "Delete Test Namespaces"
                
