pr: none
trigger: none

stages:
  - stage: connect_to_scale_cluster
    displayName: "Connect to existing cluster cilium-scale"
    jobs:
      - job: create_aks_cluster_with_cilium
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials --resource-group cilium-scale --name cilium-scale
                echo "verify there are currently 0 nodes"
                kubectl get node
                kubectl get pod -A
            name: "ConnectToCluster"
            displayName: "Connect to cilium-scale"
  # - stage: scale_up_cluster
  #   displayName: "Scale Up Cluster"
  #   jobs:
  #     - job: scale
  #       steps:
  #         - task: AzureCLI@1
  #           inputs:
  #             azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
  #             scriptLocation: "inlineScript"
  #             scriptType: "bash"
  #             addSpnToEnvironment: true
  #             inlineScript: |
  #               az aks nodepool scale --name nodepool1 --cluster-name cilium-scale --resource-group cilium-scale --node-count 2000
  #           name: "ScaleUpCluster"
  #           displayName: "Scale Up Cluster to 2000 Nodes"
  # - stage: scale_down_cluster
  #   displayName: "Scale Down Cluster"
  #   jobs:
  #     - job: scale
  #       steps:
  #         - task: AzureCLI@1
  #           inputs:
  #             azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
  #             scriptLocation: "inlineScript"
  #             scriptType: "bash"
  #             addSpnToEnvironment: true
  #             inlineScript: |
  #               az aks nodepool scale --name nodepool1 --cluster-name cilium-scale --resource-group cilium-scale --node-count 0
  #           name: "ScaleDownCluster"
  #           displayName: "Scale Down Cluster to 0 Nodes" 
                
