pr: none
trigger: none

stages:
  - stage: Connect to Scale Cluster
    displayName: "Connect to existing cluster cilium-scale"
    jobs:
      - job: connect_to_scale_test_cluster
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                echo "verify there are currently nodes"
                kubectl get node
                kubectl get pod -A
            name: "ConnectToCluster"
            displayName: "Connect to cilium-scale"
  - stage: Update Cilium Version
    displayName: "Update Cilium Version and Restart Nodes"
    jobs:
      - job: update_version
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                echo "Redeploy all cilium components and update cilium version. Redeploy all to catch all changes between versions"
                echo "deploy Cilium ConfigMap"
                kubectl apply -f cilium/configmap.yaml
                kubectl apply -f test/integration/manifests/cilium/cilium-config.yaml
                echo "install Cilium ${CILIUM_VERSION_TAG}"
                envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/daemonset.yaml | kubectl apply -f -
                envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/deployment.yaml | kubectl apply -f -
                kubectl apply -f test/integration/manifests/cilium/cilium-agent
                kubectl apply -f test/integration/manifests/cilium/cilium-operator
                vmss_name=$(az vmss list -g MC_${CLUSTER}_${CLUSTER}_$(LOCATION) --query "[].name" -o tsv)
                make -C ./hack/aks restart-vmss AZCLI=az CLUSTER=${CLUSTER} REGION=$(LOCATION) VMSS_NAME=$vmss_name
                kubectl get node 
                kubectl get pod -A
            name: "UpdateCiliumVersion"
            displayName: "Update Cilium Version"
  - stage: Scale Up Cluster
    displayName: "Scale Up Cluster"
    jobs:
      - job: scale_up
        steps:
          - template: ../scale-test-templates/scale-up-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
  - stage: Label Nodes
    displayName: "Label Nodes for Testing"
    jobs:
      - job: label_nodes
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Set node label scale-test=true and connectivity-test=true for testing"
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                cd test/scale 
                chmod +x label-nodes.sh
                ./label-nodes.sh
            name: "LabelNodes"
            displayName: "Label all Nodes"
  - stage: Scale Cluster Deployments
    displayName: "Scale deploments for Network Policies Check"
    jobs:
      - job: scale_deployments
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "scale deployment and to prep for network policies test"
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                cd test/scale
                chmod +x test-scale.sh
                ./test-scale.sh --max-kwok-pods-per-node=0 --num-kwok-deployments=0 --num-kwok-replicas=0 --max-real-pods-per-node=200 --num-real-deployments=1 --num-real-replicas=80 --num-network-policies=2000 --num-unapplied-network-policies=2000 --num-unique-labels-per-pod=0 --num-unique-labels-per-deployment=5 --num-shared-labels-per-pod=3 --num-real-services=1 --delete-labels
            name: "scaling"
            displayName: "Run scale script"
  - stage: Test Network Policy Connectivity
    displayName: "Test Network Policies"
    jobs:
      - job: network_policies
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Run network policies test"
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                cd test/scale/connectivity
                chmod +x test-connectivity.sh
                ./test-connectivity.sh --num-scale-pods-to-verify=40 --max-wait-for-initial-connectivity=600 --max-wait-after-adding-netpol=120
            name: "TestNetworkPolicies"
            displayName: "Network Policies Scale Test"
  - stage: Test LB Services
    displayName: "Test Load Balancing Service"
    jobs:
      - job: deploy_service
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
                cd test/scale
                chmod +x test-scale.sh
                ./test-scale.sh --max-kwok-pods-per-node=0 --num-kwok-deployments=0 --num-kwok-replicas=0 --max-real-pods-per-node=200 --num-real-deployments=1 --num-real-replicas=60 --num-network-policies=10 --num-unapplied-network-policies=10 --num-unique-labels-per-pod=0 --num-unique-labels-per-deployment=5 --num-shared-labels-per-pod=3 --num-real-services=1 --delete-labels
            name: "TestLBServices"
            displayName: "LB Services Scale Test"
  - stage: Scale Down Cluster
    displayName: "Scale Down Cluster"
    jobs:
      - job: scale_down
        steps:
          - template: ../scale-test-templates/scale-down-cluster.yaml
            parameters:
              clusterName: "cilium-scale"
  - stage: Delete Test Namespaces
    displayName: "Delete Test Namespaces"
    jobs:
      - job: delete_namespaces
        steps:
        - task: AzureCLI@1
          inputs:
            azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
            scriptLocation: "inlineScript"
            scriptType: "bash"
            addSpnToEnvironment: true
            inlineScript: |
              echo "scale deployment and test network policies"
              az aks get-credentials --resource-group ${CLUSTER} --name ${CLUSTER}
              kubectl delete ns scale-test
              kubectl delete ns connectivity-test
              kubectl get ns
          name: "DeleteTestNamespaces"
          displayName: "Delete Test Namespaces"
                
