pr: none
trigger: none

stages:
  - stage: connect_to_scale_cluster
    displayName: "Connect to existing cluster cilium-scale"
    jobs:
      - job: connect_to_scale_test_cluster
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                az aks get-credentials --resource-group cilium-scale --name cilium-scale
                echo "verify there are currently nodes"
                kubectl get node
                kubectl get pod -A
            name: "ConnectToCluster"
            displayName: "Connect to cilium-scale"
  - stage: scale_up_cluster
    displayName: "Scale Up Cluster"
    jobs:
      - job: scale_up
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Scale nodes up to 1000 for testing"
                az aks nodepool scale --name nodepool1 --cluster-name cilium-scale --resource-group cilium-scale --node-count 1000
            name: "ScaleUpCluster"
            displayName: "Scale Up Cluster to 1000 Nodes"
  - stage: label_nodes
    displayName: "Label Nodes for Testing"
    jobs:
      - job: label_nodes
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Set node label scale-test=true for testing"
                cd test/scale 
                chmod +x label-nodes.sh
                ./label-nodes.sh
            name: "LabelNodes"
            displayName: "Label all Nodes"
  - stage: test_network_policies
    displayName: "Test Network Policies"
    jobs:
      - job: network_policies
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "deploy network policies"
                echo "this is where we'll call test-scale for network policies"
            name: "TestNetworkPolicies"
            displayName: "Network Policies Scale Test"
  - stage: test_lb_services
    displayName: "Test Load Balancing Service"
    jobs:
      - job: deploy_service
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Set 1 deployment, 60 replicas, and 1 service."
                echo "this is where we'll call test-scale for services"
            name: "TestLBServices"
            displayName: "LB Services Scale Test"
  - stage: scale_down_cluster
    displayName: "Scale Down Cluster"
    jobs:
      - job: scale_down
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Tests completed. Scale back down to 100 nodes."
                az aks nodepool scale --name nodepool1 --cluster-name cilium-scale --resource-group cilium-scale --node-count 100
            name: "ScaleDownCluster"
            displayName: "Scale Down Cluster to 100 Nodes" 
                
