parameters:
  - name: resourceGroup
    type: string
    default: ''
  - name: clusterName
    type: string
    default: ''
  - name: artifactDir
    type: string
    default: "$(Build.ArtifactStagingDirectory)/throughput"

jobs:
  - job: SetupNetperf
    displayName: "Setup Netperf"
    steps:
      - task: AzureCLI@2
        name: throughput_setup
        displayName: "Setup Netperf"
        inputs:
          azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
          scriptLocation: "inlineScript"
          scriptType: "bash"
          addSpnToEnvironment: true
          inlineScript: |
            az aks get-credentials --resource-group ${{ parameters.resourceGroup }} --name ${{ parameters.clusterName }}
            kubectl apply -f hack/manifests/k8s-netperf.yaml

