{
 "title": "kube-system/azure-cns",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"kube-system/azure-cns\"}, instance)"
    }
   },
   {
    "name": "subnet_mask",
    "query": {
     "query": "label_values(cx_ipam_max_ips{job=\"kube-system/azure-cns\"}, subnet_cidr)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Per Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instance Status",
   "type": "gauge",
   "description": "CNS instance liveness according to /metrics on each instance.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kube-system/azure-cns\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$instance Requested IPs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cx_ipam_requested_ips{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "$instance Reserved IPs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cx_ipam_total_ips{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "$instance Used IPs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cx_ipam_pod_allocated_ips{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "IP utilization",
   "type": "timeseries",
   "description": "Cluster IP utilization displayed as IPs assigned to Pods vs total IPs allocated to the Node, by Instance.",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "cx_ipam_requested_ips{instance=~\"$instance\"}",
     "legendFormat": "Requested by CNS"
    },
    {
     "expr": "cx_ipam_total_ips{instance=~\"$instance\"}",
     "legendFormat": "Allocated to Node"
    },
    {
     "expr": "cx_ipam_pod_allocated_ips{instance=~\"$instance\"}",
     "legendFormat": "Assigned to Pods"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Reserved IPs",
   "type": "barchart",
   "description": "Total IPs reserved by CNS by Node",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum (cx_ipam_total_ips) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Assigned Pod IPs",
   "type": "barchart",
   "description": "All IPs in use by Pods by Node",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum (cx_ipam_pod_allocated_ips) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reserved vs Assigned Pod IPs",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 20 },
   "targets": [
    { "expr": "sum(cx_ipam_total_ips)", "legendFormat": "Reserved IPs" },
    { "expr": "sum(cx_ipam_pod_allocated_ips)", "legendFormat": "Used IPs" }
   ]
  },
  {
   "title": "Cluster Subnet Utilization %",
   "type": "gauge",
   "description": "How much of the Subnet this Cluster is using.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (cx_ipam_pod_allocated_ips) / (2^(32-$subnet_mask))"
    }
   ]
  },
  {
   "title": "Cluster Subnet Utilization",
   "type": "timeseries",
   "description": "How much of the Subnet this Cluster is using.",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "2^(32-$subnet_mask)", "legendFormat": "IPs available in /$subnet_mask" },
    { "expr": "sum(cx_ipam_pod_allocated_ips)", "legendFormat": "Used IPs" }
   ]
  },
  {
   "title": "Node Headroom",
   "type": "gauge",
   "description": "The most Nodes that could be added to the Cluster given the current Subnet capacity.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((2^(32-$subnet_mask))-(sum(cx_ipam_total_ips)))/(min(cx_ipam_batch_size))"
    }
   ]
  }
 ]
}