apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - serviceaccount.yaml
  - rbac.yaml

secretGenerator:
- name: npm-ca-certs
  options:
    disableNameSuffixHash: true
  files:
  - ca.crt
