#####################################################################################################################
# Upload Signed Windows Binaries (Jobs) Template
#####################################################################################################################
# Signed Windows binaries are first downloaded from the the artifacts of the dependent pipeline and propagated to storage.
#
# Matrix Schema:
#   [target-archive-identifier] - An identifying value for the package to upload. Cannot be duplicated.
#     artifact     - The artifact from the dependent pipeline (Networking-Aquarius-Official) corresponding to the target package to publish.
#     file_pattern - A filter for any unneccesary files that might also be included in the artifact. 
#                    Equal to 'patterns' in [artifact download task](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-download?view=azure-pipelines).
#     name - Friendly name to call the package. Used only for display.
#
# Parameters:
#   storage_service_connection (string) - The AzureRM service connection corresponding to the select storage account.
#   storage_account            (string) - The storage account to upload the binary to.
#   storage_container          (string) - The container to upload the blob to.
#   storage_path               (string) - The path to append to the blob name. Batch uploads are used.
#####################################################################################################################
parameters:
- name: storage_service_connection
  type: string
- name: storage_account
  type: string
- name: storage_container
  type: string
- name: storage_path
  type: string

jobs:
- job: 
  displayName: Upload .EXE - ${{ parameters.storage_account }}/${{ parameters.storage_container }}
  workspace:
    clean: all
  strategy:
    matrix:
      azure_cni_singletenancy:
        artifact: drop_sign_binaries_sign_each_binary
        file_pattern: "@(azure-vnet-cni-)@(windows)*.zip"
        name: Azure CNI Single Tenancy
      azure_cni_multitenancy:
        artifact: drop_sign_binaries_sign_each_binary
        file_pattern: "@(azure-vnet-cni-multitenancy-)*.zip"
        name: Azure CNI Multi Tenancy
      azure_cni_swift:
        artifact: drop_sign_binaries_sign_each_binary
        file_pattern: "@(azure-vnet-cni-swift-)@(windows)*.zip"
        name: Azure CNI Swift Single Tenancy
      azure_cni_overlay:
        artifact: drop_sign_binaries_sign_each_binary
        file_pattern: "@(azure-vnet-cni-overlay-)@(windows)*.zip"
        name: Azure CNI Overlay Single Tenancy
  steps:
  - download: networking_aquarius_official
    artifact: $(artifact)
    patterns: $(file_pattern)

  - template: ./upload-batch-binaries.steps.yaml
    parameters:
      source_path: $(Pipeline.Workspace)/networking_aquarius_official/$(artifact)
      blob_prefix: ${{ parameters.storage_path }}
      storage_account: ${{ parameters.storage_account }}
      storage_container: ${{ parameters.storage_container }}
      storage_service_connection: ${{ parameters.storage_service_connection }}
      addtl_opts: '--overwrite'
