parameters:
- name: storage_service_connection
  type: string
- name: storage_account
  type: string
- name: storage_container
  type: string
- name: storage_path
  type: string

jobs:
# The $(Build.ArtifactStagingDirectory) and $(Common.TestResultsDirectory) are always deleted and recreated prior to every build.
- job: 
  displayName: Upload .EXE - ${{ parameters.storage_account }}/${{ parameters.storage_container }}
  workspace:
    clean: all
  dependsOn: prepare
#  variables:
#    VERSION: $[ dependencies.prepare.outputs['get_version.version'] ]
  uses:
    repositories:
      - self
  strategy:
    matrix:
      azure_cni_singletenancy:
        artifact: drop_sign_binaries_sign_each_binary
        file_pattern: "@(azure-vnet-cni-)@(windows)*.zip"
        name: Azure CNI Single Tenancy
      azure_cni_multitenancy:
        artifact: drop_sign_binaries_sign_each_binary
        file_pattern: "@(azure-vnet-cni-multitenancy-)*.zip"
        name: Azure CNI Multi Tenancy
      azure_cni_swift:
        artifact: drop_sign_binaries_sign_each_binary
        file_pattern: "@(azure-vnet-cni-swift-)@(windows)*.zip"
        name: Azure CNI Swift Single Tenancy
      azure_cni_overlay:
        artifact: drop_sign_binaries_sign_each_binary
        file_pattern: "@(azure-vnet-cni-overlay-)@(windows)*.zip"
        name: Azure CNI Overlay Single Tenancy
  steps:
  - checkout: self
    fetchDepth: 1
    clean: true

  - template: ./get-utility-scripts.steps.yaml
    parameters:
      service_connection: ${{ parameters.storage_service_connection }}

  - download: networking_aquarius_official
    artifact: $(artifact)
    patterns: $(file_pattern)

  - template: ./upload-batch-binaries.steps.yaml
    parameters:
      source_path: $(Pipeline.Workspace)/networking_aquarius_official/$(artifact)
      blob_prefix: ${{ parameters.storage_path }}
      storage_account: ${{ parameters.storage_account }}
      storage_container: ${{ parameters.storage_container }}
      storage_service_connection: ${{ parameters.storage_service_connection }}
      addtl_opts: '--overwrite'
