# Use a minimal image as a parent image
FROM mcr.microsoft.com/windows/nanoserver:1809
ARG TELEMETRY_BUILD_DIR
ARG TELEMETRY_CONF_DIR

# Install plugin
COPY $TELEMETRY_BUILD_DIR/azure-vnet-telemetry.exe /Windows/System32
COPY $TELEMETRY_CONF_DIR/azure-vnet-telemetry.config /Windows/System32

WORKDIR /Windows/System32

# Run below command by default when the container starts.
ENTRYPOINT ["/Windows/System32/azure-vnet-telemetry.exe", "-d", "/Windows/System32"]