---
openapi: "3.0.0"
info:
  version: 0.1.0
  title: Container Networking Service (CNS)
paths:
  /network/nmagentsupportedapis:
    post:
      description: |
        Returns the supported API names from NMAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NMAgentSupportedAPIsRequest'
      responses:
        '200':
          description: The list of supported API names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NMAgentSupportedApisResponse'

  /network/deletenetworkcontainer:
    post:
      summary: Removes the Network Container from CNS's purview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteContainerRequest"
      responses:
        '200':
          description: >-
            The delete request was processed. This does not indicate the request
            was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteContainerResponse'

  /network/setorchestratortype:
    post:
      description: >-
        Sets the orchestrator type for a given node
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/SetOrchestratorTypeRequest"
      responses:
        '200':
          description: The request was submitted. This does not indicate success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

  /network/createorupdatenetworkcontainer:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/CreateNetworkContainerRequest"
      responses:
        '200':
          description: >-
            The request was submitted. This does not indicate success. You
            must check the value of the return code in the response body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
  /network/publishnetworkcontainer:
    post:
      summary: Publish NetworkContainer via NMAgent
      description: >-
        Publishes the provided network container via the NMAgent running on the
        node CNS is running on. CNS acts as a proxy for this request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublishNetworkContainerRequest"
      responses:
        '200':
          description: >-
            The request was submitted. Check the return code for success or
            failure information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublishNetworkContainerResponse"

  /network/unpublishnetworkcontainer:
    post:
      summary: Unpublish Network Container via NMAgent
      description: >-
        Unpublishes the network container through the NMAgent running on the CNS
        node. CNS acts as a proxy to NMAgent.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UnpublishNetworkContainerRequest"
      responses:
        '200':
          description: >-
            The request was submitted. Check the response code for more
            information on success or failure.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UnpublishNetworkContainerResponse"

  /ibdevices/pod:
    post:
      summary: Assigns IB devices to a pod
      description: >-
        Assigns the specified IB devices to the pod identified by PodID. The
        MAC addresses of the devices are provided in the request body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssignIBDevicesToPodRequest"
      responses:
        '200':
          description: >-
            The request passed initial validation and CNS was able to propagate its state.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssignIBDevicesToPodResponse"
        '404':
          description: >-
            The pod specified by PodID was not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssignIBDevicesToPodResponse"
        '400':
          description: >-
            One of the IB devices specified is not available
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssignIBDevicesToPodResponse"
  
  /ibdevices/{macaddress}:
    get:
      summary: Get status of an IB device
      description: >-
        Retrieves the current status of the specified IB device.
      parameters:
        - name: macaddress
          in: path
          required: true
          description: The MAC address of the IB device (with colons ":")
          schema:
            type: string
      responses:
        '200':
          description: >-
            The request was successful and the status of the IB device is returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetIBDeviceStatusResponse"
        '404':
          description: >-
            The IB device specified by MAC address was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetIBDeviceStatusResponse"

components:
  schemas:
    UnpublishNetworkContainerResponse:
      type: object
      properties:
        Response:
          $ref: "#/components/schemas/Response"
        UnpublishErrorStr:
          type: string
        UnpublishStatusCode:
          type: string
        UnpublishResponseBody:
          type: string
          description: >-
            The base64 encoded response body from NMAgent

    PublishNetworkContainerResponse:
      type: object
      properties:
        Response:
          $ref: "#/components/schemas/Response"
        PublishErrStr:
          type: string
        PublishStatusCode:
          type: string
        PublishResponseBody:
          type: string
          description: >-
            The base64 encoded response body from NMAgent

    UnpublishNetworkContainerRequest:
      type: object
      properties:
        NetworkID:
          type: string
        NetworkContainerID:
          type: string
        JoinNetworkURL:
          type: string
        DeleteNetworkContainerURL:
          type: string

    PublishNetworkContainerRequest:
      type: object
      properties:
        NetworkID:
          type: string
        NetworkContainerID:
          type: string
        JoinNetworkURL:
          type: string
        CreateNetworkContainerURL:
          type: string
        CreateNetworkContainerRequestBody:
          type: string
          description: >-
            The base64 encoded value of the create network container request
            body
    CreateNetworkContainerRequest:
      type: object
      properties:
        Version:
          type: string
        NetworkContainerType:
          type: string
        NetworkContainerid:
          type: string
        PrimaryInterfaceIdentifier:
          type: string
        AuthorizationToken:
          type: string
        LocalIPConfiguration:
          $ref: "#/components/schemas/IPConfiguration"
        OrchestratorContext:
          type: object
        IPConfiguration:
          $ref: "#/components/schemas/IPConfiguration"
        SecondaryIPConfigs:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/SecondaryIPConfig"
        MultiTenancyInfo:
          type: object
          properties:
            EncapType:
              type: string
              description: >-
                The encapsulation type for multitenancy.
            ID:
              type: integer
              description: >-
                The identifier associated with the encapsulation type specified.
                For VLAN, this would be the VLAN ID. For VXLAN, the VXLAN id,
                for GRE, the gre-key, etc.
        CnetAddressSpace:
          type: array
          items:
            $ref: "#/components/schemas/IPSubnet"
        Routes:
          type: array
          items:
            $ref: "#/components/schemas/Route"
        AllowHostToNCCommunication:
          type: boolean
        AllowNCToHostCommunication:
          type: boolean
        EndpointPolicies:
          type: array
          items:
            $ref: "#/components/schemas/NetworkContainerRequestPolicy"

    NetworkContainerRequestPolicy:
      type: object
      description: >-
        Specifies policies associated with a request to create a network
        container.
      properties:
        Type:
          type: string
        EndpointType:
          type: string
        Settings:
          type: object

    Route:
      type: object
      properties:
        IPAddress:
          type: string
        GatewayIPAddress:
          type: string
        InterfaceToUse:
          type: string

    SecondaryIPConfig:
      type: object
      properties:
        IPAddress:
          type: string
        NCVersion:
          type: integer

    IPSubnet:
      type: object
      properties:
        IPAddress:
          type: string
        PrefixLength:
          type: integer
          minimum: 0
          maximum: 255
    IPConfiguration:
      type: object
      properties:
        IPSubnet:
          $ref: "#/components/schemas/IPSubnet"
        DNSServers:
          type: array
          items:
            type: string
        GatewayIPAddress:
          type: string
    SetOrchestratorTypeRequest:
      type: object
      required:
        - OrchestratorType
        - NodeID
      properties:
        OrchestratorType:
          type: string
          enum:
            - "Kubernetes"
            - "ServiceFabric"
            - "Batch"
            - "DBforPostgreSQL"
            - "AzureFirstParty"
            - "KubernetesCRD"
        DncPartitionKey:
          type: string
        NodeID:
          type: string

    NMAgentSupportedAPIsRequest:
      type: object
      required:
        - GetNmAgentSupportedApisURL
      properties:
        GetNmAgentSupportedApisURL:
          type: string

    DeleteContainerRequest:
      type: object
      required:
        - NetworkContainerid
      properties:
        NetworkContainerid:
          type: string

    NMAgentSupportedApisResponse:
      type: object
      required:
        - Response
        - SupportedApis
      properties:
        Response:
          $ref: "#/components/schemas/Response"
        SupportedApis:
          type: array
          items:
            type: string

    DeleteContainerResponse:
      type: object
      required:
        - Response
      properties:
        Response:
          $ref: "#/components/schemas/Response"

    Response:
      type: object
      required:
        - ReturnCode
        - Message
      properties:
        ReturnCode:
          type: integer
          description: The CNS Error Code
        Message:
          type: string
          description: The error message

    AssignIBDevicesToPodRequest:
      type: object
      required:
        - PodID
        - MACAddresses
      properties:
        PodID:
          type: string
          description: podname-podnamespace of which pod to attach these devices to
        MACAddresses:
          type: array
          description: MAC addresses of IB devices such as "60:45:bd:a4:b5:7a"
          items:
            type: string

    AssignIBDevicesToPodResponse:
      type: object
      required:
        - ErrorCode
        - Message
      properties:
        ErrorCode:
          $ref: "#/components/schemas/ErrorCode"
        Message:
          type: string
          description: Human-readable message or error description

    GetIBDeviceStatusResponse:
      type: object
      required:
        - MACAddress
        - PodID
        - Status
        - ErrorCode
        - Message
      properties:
        MACAddress:
          type: string
          description: MAC address of the IB device
        PodID:
          type: string
          description: podname-podnamespace of the pod to which the device is assigned, if any
        Status:
          $ref: "#/components/schemas/Status"
        ErrorCode:
          $ref: "#/components/schemas/ErrorCode"
        Message:
          type: string
          description: Human-readable message or error description
    
    ErrorCode:
      type: integer
      description: Pre-defined error code of what went wrong, if anything (see cns/types/infiniband/errorcodes.go)
      oneOf:
      - title: Success
        const: 0
        description: Successful operation
      - title: PodNotFound
        const: 1
        description: Pod not found
      - title: DeviceUnavailable
        const: 2
        description: Device is unavailable
      - title: DeviceNotFound
        const: 3
        description: Device not found
      - title: AnnotationNotFound
        const: 4
        description: Annotation not found on pod
      - title: PodAlreadyAllocated
        const: 5
        description: Pod was already assigned IB devices (and new ones don't match)
      - title: InternalProgrammingError
        const: 6
        description: Something went wrong programming the devices
      
    Status:
      type: integer
      description: Status of IB device (see cns/types/infiniband/status.go)
      oneOf:
      - title: Available
        const: 0
        description: Device is available for use
      - title: ProgrammingPending
        const: 1
        description: Programming of device is pending
      - title: ProgrammingFailed
        const: 2
        description: Programming of device failed
      - title: ProgrammingComplete  
        const: 3
        description: Programming of device is complete
      - title: ReleasePending
        const: 4
        description: Release of device is pending
