parameters:
  dependsOn: ""
  name: ""
  clusterType: ""
  clusterName: ""
  nodeCount: ""
  vmSize: ""
  windowsVMSize: ""
  os: windows
  arch: ""

# CNIv1
# + Should be able to scale up/down the pods successfully certain number of times.
# + Node reboot scenarios should be covered.
# The HNS state should be validated with that of CNI state.
# + Pods should have ips assigned and connectivity/datapath test should be present.

stages:
  - stage: create_${{ parameters.name }}
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['SetEnvVars.commitID'] ]
      npmVersion: $[ stagedependencies.setup.env.outputs['SetEnvVars.npmVersion'] ]
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn:
      - setup
    displayName: "Create Cluster - ${{ parameters.clusterName }}"
    jobs:
      - job: create_aks_cluster_with_${{ parameters.name }}
        steps:
          - template: ../load-test-templates/create-cluster-template.yaml
            parameters:
              clusterType: ${{ parameters.clusterType }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              nodeCount: ${{ parameters.nodeCount }}
              vmSize: ${{ parameters.vmSize }}
              windowsVMSize: ${{ parameters.windowsVMSize }}
              region: $(LOCATION)
  - stage: ${{ parameters.name }}
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['SetEnvVars.commitID'] ]
      npmVersion: $[ stagedependencies.setup.env.outputs['SetEnvVars.npmVersion'] ]
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn:
      - create_${{ parameters.name }}
      - publish
      - setup
    displayName: "CNIv1 Test - ${{ parameters.name }}"
    jobs:
      - job: update_cni
        strategy:
          matrix:
            cni_dropgz_windows2022_amd64:
              os: windows
              arch: amd64
              os_version: ltsc2022
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                set -ex
                make -C ./hack/aks set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(commitID)
                make -C ./hack/aks azcfg AZCLI=az REGION=$(LOCATION)
                export DROP_GZ_URL=$( make cni-dropgz-test-image-name-and-tag OS=${{ parameters.os }} ARCH=${{ parameters.arch }} CNI_DROPGZ_VERSION=$(dropgzVersion))
                envsubst < ./test/integration/manifests/cni/cni-installer-v1-windows.yaml | kubectl apply -f -
            name: "UploadCNI"
            displayName: "Upload CNI"
          - script: |
              set -ex
              kubectl rollout status daemonset/azure-cni-windows -n kube-system
              kubectl get pods -A
            name: "WaitForCNI"
            displayName: "Wait For CNI"
  - stage: datapath_tests
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn: update_cni
    displayName: "Datapath Test - Windows"
    jobs:
      - template: ../k8s-e2e/k8s-e2e-job-template.yaml
        parameters:
          sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
          clusterName: ${{ parameters.clusterName }}-$(make revision)
          os: ${{ parameters.os }}
          datapath: true
          dns: true
          portforward: true
          hybridWin: true
          service: true
          hostport: true
  - stage: pod_deployment_windows
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn: datapath_tests
    displayName: "Pod Deployment"
    jobs:
      - job: deploy_pods
        displayName: "Scale Test"
        dependsOn: update_cni
        steps:
          - template: ../load-test-templates/pod-deployment-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              scaleup: ${WINDOWS_SCALEUP}
              os: ${{ parameters.os }}
              iterations: ${WINDOWS_ITERATIONS}
              nodeCount: ${{ parameters.nodeCount }}
  - stage: validate_state_windows
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    dependsOn: pod_deployment_windows
    displayName: "Validate State"
    jobs:
      - job: validate_state
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - template: ../load-test-templates/validate-state-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              cni: ${{ parameters.cni }}

  - stage: npm
    dependsOn:
      - validate_state_windows
      - setup
    displayName: NPM|CNI Release Test
    variables:
      npmVersion: $[ stagedependencies.setup.env.outputs['SetEnvVars.npmVersion'] ]
    jobs:
      - template: ../../npm/npm-cni-integration-test.yaml
        parameters:
          clusterName: ${{ parameters.clusterName }}
          os: ${{ parameters.os }}
          sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
          os_version: 'ltsc2022'
          tag: $(npmVersion)

  - stage: delete_resources
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    displayName: "Delete Resources"
    dependsOn:
      - npm
    jobs:
      - job: delete_resources
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                echo "Delete load-test Namespace"
                make -C ./hack/aks set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(commitID)
                kubectl delete ns load-test
                kubectl cluster-info
                kubectl get po -owide -A
            name: "recover"
            displayName: "Delete test Namespaces"
      - template: ../k8s-e2e/k8s-e2e-job-template.yaml
        parameters:
          sub: $(SUB_AZURE_NETWORK_AGENT_BUILD_VALIDATIONS)
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          os: ${{ parameters.os }}
          dependsOn: recover
          datapath: true
          dns: true
          portforward: true
          hybridWin: true
          service: true
          hostport: true
      - template: ../../npm/npm-cni-integration-test.yaml
        parameters:
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          os: ${{ parameters.os }}
          sub: $(SUB_AZURE_NETWORK_AGENT_BUILD_VALIDATIONS)
          os_version: 'ltsc2022'
          tag: $(npmVersion)
          dependsOn: cni_k8se2e
