parameters:
  name: ""
  displayName: ""
  clusterType: ""
  clusterName: ""
  vmSize: ""
  k8sVersion: ""
  dependsOn: ""

stages:
  - stage: ${{ parameters.clusterName }}
    displayName: Create Cluster - ${{ parameters.displayName }}
    dependsOn:
      - ${{ parameters.dependsOn }}
      - setup
      - publish
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
      CNS_VERSION: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.cnsVersion'] ]
      AZURE_IPAM_VERSION: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.azureIpamVersion'] ]
      CNI_VERSION: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.cniVersion'] ]
      CNS_IMAGE_REPO: ACN
      IPAM_IMAGE_REPO: ACN
      CNI_IMAGE_REPO: ACN
      CNS_IMAGE_NAME_OVERRIDE: azure-cns
      IPAM_IMAGE_NAME_OVERRIDE: azure-ipam
      CNI_IMAGE_NAME_OVERRIDE: azure-cni
      CILIUM_LOG_COLLECTOR_IMAGE_REGISTRY_OVERRIDE: acnpublic.azurecr.io
      CILIUM_LOG_COLLECTOR_VERSION_TAG_OVERRIDE: $[ stageDependencies.setup.env.outputs['EnvironmentalVariables.ciliumLogCollectorVersion'] ]
      IPV6_IMAGE_REGISTRY: acnpublic.azurecr.io
    jobs:
      - job: ${{ parameters.name }}
        displayName: Cluster - ${{ parameters.name }}
        steps:
          - template: ../../templates/create-cluster-steps.yaml
            parameters:
              clusterType: ${{ parameters.clusterType }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              vmSize: ${{ parameters.vmSize }}
              k8sVersion: ${{ parameters.k8sVersion }}
              region: $(REGION_AKS_CLUSTER_TEST)
          - template: ../../templates/network-install.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              networkType: cilium-dualstack
              azureIpamVersion: $(AZURE_IPAM_VERSION)
              cnsVersion: $(CNS_VERSION)
              cniVersion: $(CNI_VERSION)
              installFlag: INSTALL_OVERLAY
  - stage: ${{ parameters.name }}
    displayName: E2E - ${{ parameters.displayName }}
    dependsOn:
    - setup
    - publish
    - ${{ parameters.clusterName }}
    variables:
      GOPATH: "$(Agent.TempDirectory)/go" # Go workspace path
      GOBIN: "$(GOPATH)/bin" # Go binaries path
      modulePath: "$(GOPATH)/src/github.com/Azure/azure-container-networking"
      commitID: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.commitID'] ]
      CNS_VERSION: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.cnsVersion'] ]
      AZURE_IPAM_VERSION: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.azureIpamVersion'] ]
      CNS_IMAGE_NAME_OVERRIDE: azure-cns
      IPAM_IMAGE_NAME_OVERRIDE: azure-ipam
      IPV6_IMAGE_REGISTRY: acnpublic.azurecr.io
    pool:
      name: $(BUILD_POOL_NAME_DEFAULT)
    jobs:
      - job: ${{ parameters.name }}
        displayName: Cilium Dualstack Overlay Test Suite - (${{ parameters.name }})
        timeoutInMinutes: 120
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands:
          - agent.os -equals Linux
          - Role -equals $(CUSTOM_E2E_ROLE)
        steps:
          - template: cilium-dualstackoverlay-e2e-step-template.yaml
            parameters:
              name: ${{ parameters.name }}
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              scaleup: 100

      - template: ../../cni/k8s-e2e/k8s-e2e-job-template.yaml
        parameters:
          sub: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
          clusterName: ${{ parameters.clusterName }}-$(commitID)
          os: ${{ parameters.os }}
          cni: cilium
          dependsOn: ${{ parameters.name }}
          dualstack: true
          dns: true
          portforward: true
          service: true

      - job: failedE2ELogs
        displayName: "Failure Logs"
        dependsOn:
          - ${{ parameters.name }}
          - cni_${{ parameters.os }}
        condition: failed()
        steps:
          - template: ../../templates/log-template.yaml
            parameters:
              clusterName: ${{ parameters.clusterName }}-$(commitID)
              os: ${{ parameters.os }}
              cni: cilium
