trigger:
- main

parameters:
  - name: subscriptionId
    type: string
    default: "37deca37-c375-4a14-b90a-043849bd2bf1"
  - name: location
    type: string
    default: "centraluseuap"
  - name: resourceGroupName
    type: string
    default: "long-run-$(date +%s)"
  - name: vmSkuDefault
    type: string
    default: "Standard_D2s_v3"
  - name: vmSkuHighNIC
    type: string
    default: "Standard_D16s_v3"
  - name: serviceConnection
    displayName: "Azure Service Connection"
    type: string
    default: "Azure Container Networking - Standalone Test Service Connection"

stages:
  - stage: AKSClusterAndNetworking
    displayName: "Stage: AKS Cluster and Networking Setup"
    jobs:
      - template: pipeline-template.yaml
        parameters:
          jobName: create-aks
          scriptPath: "infra/scripts/01_create_aks.sh"
          subscriptionId: ${{ parameters.subscriptionId }}
          location: ${{ parameters.location }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          vmSkuDefault: ${{ parameters.vmSkuDefault }}
          vmSkuHighNIC: ${{ parameters.vmSkuHighNIC }}
          dependsOn: []

      - template: pipeline-template.yaml
        parameters:
          jobName: create-vnets
          scriptPath: "infra/scripts/02_create_vnets.sh"
          subscriptionId: ${{ parameters.subscriptionId }}
          location: ${{ parameters.location }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          dependsOn: ["create-aks"]

      - template: pipeline-template.yaml
        parameters:
          jobName: create-peerings
          scriptPath: "infra/scripts/03_create_peerings.sh"
          subscriptionId: ${{ parameters.subscriptionId }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          dependsOn: ["create-vnets"]

      - template: pipeline-template.yaml
        parameters:
          jobName: create-storage
          scriptPath: "infra/scripts/04_create_storage.sh"
          subscriptionId: ${{ parameters.subscriptionId }}
          location: ${{ parameters.location }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          dependsOn: ["create-peerings"]

      - template: pipeline-template.yaml
        parameters:
          jobName: create-nsg
          scriptPath: "infra/scripts/05_create_nsg.sh"
          subscriptionId: ${{ parameters.subscriptionId }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          dependsOn: ["create-storage"]
