trigger: none

parameters:
  - name: subscriptionId
    displayName: "Azure Subscription ID"
    type: string

  - name: location
    displayName: "Deployment Region"
    type: string
    default: "eastus"

  - name: resourceGroupName
    displayName: "Resource Group Name"
    type: string
    default: "sing-$(Build.BuildId)"

  - name: cluster1Name
    displayName: "AKS Cluster 1 Name"
    type: string
    default: "aks-cluster-a"

  - name: cluster2Name
    displayName: "AKS Cluster 2 Name"
    type: string
    default: "aks-cluster-b"

  - name: nodeVmSize
    displayName: "VM Size for Node Pool (supports 7 NICs)"
    type: string
    default: "Standard_D8as_v4"

  - name: serviceConnection
    displayName: "Azure Service Connection"
    type: string
    default: "Azure-Networking-ServiceConn"

extends:
  template: templates/long-running-pipeline-template.yml
  parameters:
    subscriptionId: ${{ parameters.subscriptionId }}
    location: ${{ parameters.location }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
    cluster1Name: ${{ parameters.cluster1Name }}
    cluster2Name: ${{ parameters.cluster2Name }}
    nodeVmSize: ${{ parameters.nodeVmSize }}
    serviceConnection: ${{ parameters.serviceConnection }}
