trigger: none
pr: none

parameters:
  - name: subscriptionId
    displayName: "Azure Subscription ID"
    type: string
    default: "37deca37-c375-4a14-b90a-043849bd2bf1"

  - name: serviceConnection
    displayName: "Azure Service Connection"
    type: string
    default: "Azure Container Networking - Standalone Test Service Connection"

  - name: location
    displayName: "Deployment Region"
    type: string
    default: "eastus2"

  - name: runSetupStages
    displayName: "Create New Infrastructure Setup"
    type: boolean
    default: false

  # Setup-only parameters (only used when runSetupStages=true)
  - name: resourceGroupName
    displayName: "Resource Group Name used when Create new Infrastructure Setup is selected"
    type: string
    default: "sv2-long-run-$(Build.BuildId)"

extends:
  template: template/long-running-pipeline-template.yaml
  parameters:
    subscriptionId: ${{ parameters.subscriptionId }}
    location: ${{ parameters.location }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
    serviceConnection: ${{ parameters.serviceConnection }}
    runSetupStages: ${{ parameters.runSetupStages }}
