##########################
#### Ubuntu UnitTests ####
##########################
# Description:
# Concrete implementation of the template.unit-test.jobs.yaml class. Creates
# steps for running the full ACN suite on an Ubuntu system.


jobs:

- job: ubuntu
  displayName: "Ubuntu"
  pool:
    type: linux
  variables:
    LinuxContainerImage: onebranch.azurecr.io/linux/ubuntu-2204:latest
  steps:

  - checkout: azure-container-networking

  - template: /cicd/pkg/toolsets/template.installer.steps.yaml@self
    parameters:
      os: ubuntu
      toolset: docker-utilities

  - template: /cicd/pkg/toolsets/template.toolset.steps.yaml@self
    parameters:
      os: ubuntu
      install:
      - net-tools
      - lsof

  - bash: |
      #set -e
      #sudo netstat -tulpn
      uname -a
      pushd "$ACN_PATH"
        make tools
      popd
    displayName: "Make Test Tools"

  - bash: |
      #  set -e
      pushd "$ACN_PATH"
        COVERAGE_FILTER=$(go list --tags ignore_uncovered,ignore_autogenerated ./... | tr '\n' ',')
        echo >&2 "##vso[task.setvariable variable=COVERAGE_FILTER;]$COVERAGE_FILTER"
      popd
    displayName: 'Generate Coverage Filter'

  - task: Go@0
    retryCountOnTaskFailure: 3
    displayName: "Run Unit Tests (Ubuntu)"
    inputs:
      command: 'test'
      arguments: "-mod=readonly -buildvcs=false -tags 'unit' --skip 'TestE2E*' -coverpkg=$(COVERAGE_FILTER) -race -covermode atomic -coverprofile=coverage.out ./..."
      workingDirectory: '$(ACN_PATH)'

  - bash: |
      set -e
      netstat -tulpn
      pushd "$ACN_PATH"
         ./build/tools/go-junit-report -in coverage.out -iocopy -out "$OB_OUTPUTDIRECTORY/report-ubuntu.xml"
      popd
    displayName: 'Generate XML Coverage Report'

  # This task is performed automatically
  #
  #- task: PublishPipelineArtifact@1
  #  inputs:
  #    artifactName: report-ubuntu
  #    pathtoPublish: '$(ACN_PATH)/report-mariner.xml'
