trigger:
  - none

resources:
  pipelines:
  - pipeline: networking_aquarius_official
    source: "Networking-Aquarius-Official"
    trigger:
      branches:
        include:
          - master

variables:
  - name: buildConfiguration
    value: Release
  - name: releaseBranchName
    value: master
#  - name: STORAGE_ACCOUNT
#    value: infrae2esaue3orv
#  - name: STORAGE_CONTAINER
#    value: obp-signed-binaries
#  - name: STORAGE_SERVICE_CONNECTION
#    value: "Azure Network Agent - Test (2)"
  - name: SOURCE_REPO
    value: $[resources.repositories.self.url]
  - name: SOURCE_REF
    value: $[resources.repositories.self.version]
  - template: ./obp-signed-binaries/environment-matrix.params.yaml

stages:
- stage: prepare_stage
  displayName: Upload Nuget and Signed Binaries
  jobs:
  - job: prepare_version
    displayName: Prepare
    steps:
      - checkout: none

      - download: networking_aquarius_official
        artifact: drop_download_github
        patterns: "@(azure-vnet)"

      - bash: |
          VNET_BIN=$(find $(Pipeline.Workspace) -type f -maxdepth 4 -name 'azure-vnet')
          echo "Found Binary: $VNET_BIN"
          chmod +x "$VNET_BIN"
          VERSION=$("$VNET_BIN" --version | awk '{ print $4 }')

          echo "##vso[task.setvariable variable=version;isOutput=true;]${VERSION}"
          echo "Setting version: $VERSION"
        name: get_version
        displayName: Get Release Version

# Can use the above method or this method which uses the filename to get the version.        
#      - bash: |
#          FILENAME=$(find $(Pipeline.Workspace) -maxdepth 4 -name "azure-vnet*.zip" | head -n 1)
#          echo "Found file: $FILENAME"
#          echo "##vso[task.setvariable variable=filename]$FILENAME"
#        displayName: Verify Version-File Name
#
#      - template: ./obp-signed-binaries/get-version-from-filename.steps.yaml
#        parameters:
#          filename: $(filename)

- ${{ each env in variables.ENVIRONMENT_MATRIX }}:
  - template: ./opb-signed-binaries/upload-signed-binaries.jobs.yaml
    parameters:
      environment: ${{ env }}

#- stage: publish_nuget_stage
#  displayName: Publish Nuget Packages
#  dependsOn: prepare_stage
#  variables:
#    VERSION: $[
#  jobs:
#  - template: ./opb-signed-binaries/publish-nuget-packages.jobs.yaml
