pr:
  branches:
    include:
      - master
      - release/*
  paths:
    exclude:
      - ".devcontainer"
      - ".hooks"
      - ".vscode"
      - ".github"
      - docs

trigger:
  branches:
    include:
      - gh-readonly-queue/master/*
      - gh-readonly-queue/release/*
  tags:
    include:
      - "*"

schedules:
- cron: "0 2 * * *" # Every day at 2am
  displayName: "Official Nightly Pipeline"
  branches:
    include: ["master"]
  always: true

stages:
  - stage: setup
    displayName: ACN
    jobs:
      - job: env
        displayName: Setup
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              # To use the variables below, you must make the respective stage's dependsOn have - setup or it will not retain context of this stage
              BUILD_NUMBER=$(Build.BuildNumber)
              echo "##vso[task.setvariable variable=StorageID;isOutput=true]$(echo ${BUILD_NUMBER//./-})"
              echo "##vso[task.setvariable variable=commitID;isOutput=true]$(echo $(make revision)-$(date "+%d%H%M"))"
              echo "##vso[task.setvariable variable=Tag;isOutput=true]$(make version)"
              echo "##vso[task.setvariable variable=npmVersion;isOutput=true]$(make npm-version)"
              cat /etc/os-release
              uname -a
              sudo chown -R $(whoami):$(whoami) .
              go version
              go env
              which go
              echo $PATH
              echo "------"
              echo $(Build.QueuedBy)
              echo $(Build.Reason) # manual, PR, IndividualCI
              echo $(Build.SourceBranch)
              echo $(System.PullRequest.TargetBranch)
              echo $(System.PullRequest.targetBranchName)
            name: "EnvironmentalVariables"
            displayName: "Set environmental variables"
            condition: always()

  - template: singletenancy/cilium-overlay/cilium-overlay-e2e-job-template.yaml
    parameters:
      name: "cilium_overlay_e2e"
      displayName: Cil on AKS Overlay
      clusterType: ebpf-overlay-cilium-up
      clusterName: "cilovere2e"
      vmSize: Standard_B2ms
      k8sVersion: ""

