stages:
- stage: setup
  displayName: ACN
  variables:
    ACN_DIR: azure-container-networking
  jobs:
  - job: env
    displayName: Setup
    pool:
      type: linux
    variables:
      ob_outputDirectory: $(Build.ArtifactStagingDirectory)
      ob_artifactSuffix: _source

      ACR_DIR: $(Build.SourcesDirectory)/azure-container-networking
      BUILD_TYPE: $(IMAGE_ACR_TYPE)
    steps:
    - checkout: azure-container-networking
    - template: build/ob-prepare.steps.yaml

- ${{ if not(contains(variables['Build.SourceBranch'], 'refs/pull')) }}:
  # Cilium Overlay E2E tests
  - template: singletenancy/cilium-overlay/cilium-overlay-e2e.stages.yaml
    parameters:
      name: "cilium_overlay_e2e"
      displayName: Cilium on AKS Overlay
      clusterType: ebpf-overlay-cilium-up
      clusterName: "cilovere2e"
      vmSize: Standard_D16s_v3
      k8sVersion: ""
