trigger: none
#pr:
#  branches:
#    include:
#      - master
#      - release/*
#  paths:
#    exclude:
#      - ".devcontainer"
#      - ".hooks"
#      - ".vscode"
#      - ".github"
#      - docs
#
#
#trigger:
#  branches:
#    include:
#      - gh-readonly-queue/master/*
#  tags:
#    include:
#      - "*"

resources:
  repositories:

  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/stable

  - repository: azure-container-networking
    type: github
    name: Azure/azure-container-networking
    endpoint: 'Azure-ACN RO Service Connection'
    ref: refs/heads/feature/ob-onboard-2


variables:
  REPO_REF: $[ resources.repositories['azure-container-networking'].ref ]
  REPO_COMMIT: $[ resources.repositories['azure-container-networking'].version ]
  REPO_NAME: $[ resources.repositories['azure-container-networking'].name ]
  REPO_TYPE: $[ resources.repositories['azure-container-networking'].type ]
  CHANGESET_COMMIT: $[ resources.repositories['self'].version ]

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: "$(BUILD_POOL_NAME_DEFAULT)"
    stages:
    - template: /.pipelines/pipeline.yaml@azure-container-networking
