stages:
  - stage: sharifStage
    displayName: E2E - AKS Swiftv2 Singularity
    jobs:
      - job: swiftv2_singularity_e2e
        displayName: "Trigger Pipeline in Another Project"
        steps:
          - task: TriggerBuild@3
            inputs:
              buildDefinition: '391699'                # Pipeline ID
              buildParameters: |
                useAcnPublic=false
                cnscniversion=v1.7.7-0
                cnscniversionwindows=v1.7.7-0
                useAgentTestSubscription=false
              queueBuildForUserThatTriggeredBuild: true
              waitForQueuedBuildsToFinish: false
              authenticationMethod: 'OAuth Token'
              