parameters:
  name: ""
  dependsOn: ""

stages:
  - stage: manifolde2e
    displayName: E2E - AKS Swiftv2 Manifold
    variables:
      TAG: $[ stageDependencies.setup.env.outputs['EnvironmentalVariables.Tag'] ]
      IMAGE_REPO_PATH: $[ stageDependencies.setup.env.outputs['EnvironmentalVariables.imageRepositoryPath'] ]
    dependsOn: 
      - ${{ parameters.dependsOn }}
      - setup
    jobs:
      - job: ${{ parameters.name }}
        displayName: AKS Swiftv2 Multitenancy Manifold E2E Test Suite- (${{ parameters.name }})
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          isCustom: true
          type: linux
        steps:
          - task: TriggerBuild@3
            inputs:
              buildDefinition: '391699'
              templateParameters: 'useAcnPublic: true, cnscniversion: $(TAG), cnscniversionwindows: $(TAG), cnscniImagePrefix: $(IMAGE_REPO_PATH)/'
              useSameBranch: false
              queueBuildForUserThatTriggeredBuild: true
              branchToUse: 'refs/heads/sharifna/runner/release-gate'
              waitForQueuedBuildsToFinish: true
              authenticationMethod: 'OAuth Token'
              