stages:
  - stage: man_e2e_tests
    displayName: AKS Swiftv2 Man E2E tests
    jobs:
      - job: run_tests
        displayName: "Run Sing Runners"
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          isCustom: true
          type: linux
        steps:
          - checkout: azure-container-networking
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              scriptType: "bash"
              addSpnToEnvironment: true
              inlineScript: |
                set -e
                echo "Check az version"
          - task: TriggerBuild@3
            inputs:
              buildDefinition: '391699'                # Pipeline ID
              useSameBranch: false
              queueBuildForUserThatTriggeredBuild: true
              branchToUse: 'refs/heads/master'
              waitForQueuedBuildsToFinish: true        # Wait for completion
              authenticationMethod: 'OAuth Token'
      # - job: swiftv2_singularity_e2e
      #   displayName: "Trigger Pipeline in Another Project"
      #   steps:
      #     - task: TriggerBuild@3
      #       inputs:
      #         buildDefinition: '391699'                # Pipeline ID
      #         buildParameters: |
      #           useAcnPublic=false
      #           cnscniversion=v1.7.7-0
      #           cnscniversionwindows=v1.7.7-0
      #           useAgentTestSubscription=false
      #         queueBuildForUserThatTriggeredBuild: true
      #         waitForQueuedBuildsToFinish: false
      #         authenticationMethod: 'OAuth Token'
              