parameters:
  - name: jobName
    type: string
  - name: scriptPath
    type: string
  - name: subscriptionId
    type: string
  - name: location
    type: string
    default: ""
  - name: resourceGroupName
    type: string
  - name: vmSkuDefault
    type: string
    default: ""
  - name: vmSkuHighNIC
    type: string
    default: ""
  - name: serviceConnection
    type: string
    default: "Azure Container Networking - Standalone Test Service Connection"

jobs:
  - job: ${{ parameters.jobName }}
    displayName: "Job - ${{ parameters.jobName }}"
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: ${{ parameters.dependsOn }}
    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: "Run ${{ parameters.jobName }} script"
        inputs:
          azureSubscription: "${{ parameters.serviceConnection }}"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            set -e
            export SUBSCRIPTION_ID="${{ parameters.subscriptionId }}"
            export LOCATION="${{ parameters.location }}"
            export RG="${{ parameters.resourceGroupName }}"
            export VM_SKU_DEFAULT="${{ parameters.vmSkuDefault }}"
            export VM_SKU_HIGHNIC="${{ parameters.vmSkuHighNIC }}"

            chmod +x ${{ parameters.scriptPath }}
            ${{ parameters.scriptPath }}
