parameters:
  - name: jobName
    type: string
  - name: scriptPath
    type: string
  - name: subscriptionId
    type: string
  - name: location
    type: string
    default: ""
  - name: resourceGroupName
    type: string
  - name: vmSkuDefault
    type: string
    default: ""
  - name: vmSkuHighNIC
    type: string
    default: ""
  - name: serviceConnection
    type: string
    default: "Azure Container Networking - Standalone Test Service Connection"
  - name: dependsOn
    type: object
    default: []

jobs:
  - job: ${{ parameters.jobName }}
    displayName: "${{ parameters.jobName }}"
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: ${{ parameters.dependsOn }}
    steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: "Run ${{ parameters.jobName }} script"
        inputs:
          azureSubscription: "${{ parameters.serviceConnection }}"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            set -e
            chmod +x ${{ parameters.scriptPath }}
            ${{ parameters.scriptPath }}
            env:
              subscriptionId: ${{ parameters.subscriptionId }}
              location: ${{ parameters.location }}
              resourceGroupName: ${{ parameters.resourceGroupName }}
              vmSkuDefault: ${{ parameters.vmSkuDefault }}
              vmSkuHighNIC: ${{ parameters.vmSkuHighNIC }}