parameters:
  - name: subscriptionId
    type: string
  - name: location
    type: string
  - name: resourceGroupName
    type: string
  - name: runSetupStages
    type: boolean
    default: false

variables:
  - name: rgName
    ${{ if eq(parameters.runSetupStages, true) }}:
      value: ${{ parameters.resourceGroupName }}
    ${{ else }}:
      value: sv2-long-run-${{ parameters.location }}
  - name: vmSkuDefault
    value: "Standard_D4s_v3"
  - name: vmSkuHighNIC
    value: "Standard_D16s_v3"

stages:
  - stage: AKSClusterAndNetworking
    displayName: "Stage: AKS Cluster and Networking Setup"
    condition: eq(${{ parameters.runSetupStages }}, true)
    jobs:
      - job: CreateResourceGroup
        displayName: "Create Resource Group"
        steps:
          - task: AzureCLI@2
            displayName: "Create resource group"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Creating resource group $(rgName) in ${{ parameters.location }}"
                az group create \
                  --name "$(rgName)" \
                  --location "${{ parameters.location }}" \
                  --subscription "${{ parameters.subscriptionId }}"
                echo "Resource group created successfully."

      - job: CreateCluster
        displayName: "Create AKS Clusters"
        dependsOn: CreateResourceGroup
        steps:
          - task: AzureCLI@2
            displayName: "Create AKS clusters"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_aks.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                ${{ parameters.location }}
                $(rgName)
                $(vmSkuDefault)
                $(vmSkuHighNIC)
      
      - job: NetworkingAndStorage
        displayName: "Networking and Storage Setup"
        dependsOn: CreateCluster
        steps:
          - task: AzureCLI@2
            displayName: "Create customer vnets"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_vnets.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                ${{ parameters.location }}
                $(rgName)
                $(Build.BuildId)

          - task: AzureCLI@2
            displayName: "Create customer vnet peerings"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_peerings.sh"
              arguments: >
                $(rgName)

          - task: AzureCLI@2
            name: CreateStorageAccounts
            displayName: "Create storage accounts"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_storage.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                ${{ parameters.location }}
                $(rgName)

          - task: AzureCLI@2
            displayName: "Create Private Endpoint for Storage Account"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_pe.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                ${{ parameters.location }}
                $(rgName)
                $(CreateStorageAccounts.StorageAccount1)
          
          - task: AzureCLI@2
            displayName: "Create network security groups to restrict access between subnets"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_nsg.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                $(rgName)
                ${{ parameters.location }}
  - stage: DataPathTests
    displayName: "Stage: Swiftv2 Data Path Tests on Linux Managed Nodes"
    dependsOn: AKSClusterAndNetworking
    condition: or(eq(${{ parameters.runSetupStages }}, false), succeeded())
    variables:
      storageAccount1: $[ stageDependencies.AKSClusterAndNetworking.NetworkingAndStorage.outputs['CreateStorageAccounts.StorageAccount1'] ]
      storageAccount2: $[ stageDependencies.AKSClusterAndNetworking.NetworkingAndStorage.outputs['CreateStorageAccounts.StorageAccount2'] ]
    jobs:
      - job: CreatePods
        displayName: "Create Swiftv2 Pods"
        steps:
          - task: AzureCLI@2
            displayName: "Create Test Resources"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Setting up kubeconfig for cluster aks-1"
                az aks get-credentials \
                  --resource-group $(rgName) \
                  --name aks-1 \
                  --file /tmp/aks-1.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Setting up kubeconfig for cluster aks-2"
                az aks get-credentials \
                  --resource-group $(rgName) \
                  --name aks-2 \
                  --file /tmp/aks-2.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Verifying cluster aks-1 connectivity"
                kubectl --kubeconfig /tmp/aks-1.kubeconfig get nodes
                
                echo "==> Verifying cluster aks-2 connectivity"
                kubectl --kubeconfig /tmp/aks-2.kubeconfig get nodes
                
                echo "==> Creating test resources (8 scenarios)"
                export RG="$(rgName)"
                export BUILD_ID="$(rgName)"
                export WORKLOAD_TYPE="swiftv2-linux"
                cd ./test/integration/swiftv2/longRunningCluster
                go test -v -timeout=1h -tags=create_test

      - job: ConnectivityTests
        displayName: "Test Pod-to-Pod Connectivity"
        dependsOn: CreatePods
        steps:
          - task: AzureCLI@2
            displayName: "Run Connectivity Tests"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Setting up kubeconfig for cluster aks-1"
                az aks get-credentials \
                  --resource-group $(rgName) \
                  --name aks-1 \
                  --file /tmp/aks-1.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Setting up kubeconfig for cluster aks-2"
                az aks get-credentials \
                  --resource-group $(rgName) \
                  --name aks-2 \
                  --file /tmp/aks-2.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Running connectivity tests"
                export RG="$(rgName)"
                export BUILD_ID="$(rgName)"
                export WORKLOAD_TYPE="swiftv2-linux"
                cd ./test/integration/swiftv2/longRunningCluster
                go test -v -timeout=30m -tags=connectivity_test

      - job: PrivateEndpointTests
        displayName: "Test Private Endpoint Access"
        dependsOn: ConnectivityTests
        steps:
          - task: AzureCLI@2
            displayName: "Run Private Endpoint Tests"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Setting up kubeconfig for cluster aks-1"
                az aks get-credentials \
                  --resource-group $(rgName) \
                  --name aks-1 \
                  --file /tmp/aks-1.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Setting up kubeconfig for cluster aks-2"
                az aks get-credentials \
                  --resource-group $(rgName) \
                  --name aks-2 \
                  --file /tmp/aks-2.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Running Private Endpoint connectivity tests"
                export RG="$(rgName)"
                export BUILD_ID="$(rgName)"
                export WORKLOAD_TYPE="swiftv2-linux"
                
                STORAGE_ACCOUNT_1="$(storageAccount1)"
                STORAGE_ACCOUNT_2="$(storageAccount2)"
                
                # If variables are empty (when runSetupStages=false), discover from resource group
                if [ -z "$STORAGE_ACCOUNT_1" ] || [ -z "$STORAGE_ACCOUNT_2" ]; then
                  echo "Storage account variables not set, discovering from resource group..."
                  STORAGE_ACCOUNT_1=$(az storage account list -g $(rgName) --query "[?starts_with(name, 'sa1')].name" -o tsv)
                  STORAGE_ACCOUNT_2=$(az storage account list -g $(rgName) --query "[?starts_with(name, 'sa2')].name" -o tsv)
                  echo "Discovered: STORAGE_ACCOUNT_1=$STORAGE_ACCOUNT_1, STORAGE_ACCOUNT_2=$STORAGE_ACCOUNT_2"
                fi
                
                export STORAGE_ACCOUNT_1
                export STORAGE_ACCOUNT_2
                cd ./test/integration/swiftv2/longRunningCluster
                go test -v -timeout=30m -tags=private_endpoint_test

      - job: DeleteTestResources
        displayName: "Delete PodNetwork, PNI, and Pods"
        dependsOn: 
          - CreatePods
          - ConnectivityTests
          - PrivateEndpointTests
        condition: always()
        steps:
          - task: AzureCLI@2
            displayName: "Delete Test Resources"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Setting up kubeconfig for cluster aks-1"
                az aks get-credentials \
                  --resource-group $(rgName) \
                  --name aks-1 \
                  --file /tmp/aks-1.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Setting up kubeconfig for cluster aks-2"
                az aks get-credentials \
                  --resource-group $(rgName) \
                  --name aks-2 \
                  --file /tmp/aks-2.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Deleting test resources (8 scenarios)"
                export RG="$(rgName)"
                export BUILD_ID="$(rgName)"
                export WORKLOAD_TYPE="swiftv2-linux"
                cd ./test/integration/swiftv2/longRunningCluster
                go test -v -timeout=1h -tags=delete_test
              