name: 'Docker Base Images'
on:
  workflow_dispatch:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
        - ready_for_review
  merge_group:
    types:
      - checks_requested

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - name: go env
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
    - name: Render Dockerfiles
      run: make dockerfiles
    - name: Fail if base images are outdated
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected. Please run 'make dockerfiles' locally to update the base images."
          exit 1
        fi
