name: 'Docker Base Images'
on:
  workflow_dispatch:
  pull_request:
    types:
        - opened
        - reopened
        - synchronize
        - ready_for_review
  merge_group:
    types:
      - checks_requested

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Render Dockerfiles
      run: make dockerfiles
    - name: Fail if base images are outdated
      run: |
        git status --porcelain
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected. Please run 'make dockerfiles' locally to update the base images."
          exit 1
        fi
