name: Cyclonus network policy test

on:
  push: 
  pull_request:
  schedule:
    # run once a day at midnight
    - cron: '0 0 * * *'
env:
  KIND_VERSION: v0.9.0
  KIND_CONFIG: .github/kind-config.yaml
  CONFORMANCE_TEMPLATE: examples/kubernetes/connectivity-check/connectivity-check.yaml
  TIMEOUT: 2m
  LOG_TIME: 30m

jobs:
  cyclonus-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make NPM Image
        run: |
          VERSION=cyclonus make azure-npm-image

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.9.0"
          config: ./test/kind/kind.yaml
      
      - name: Load kind image
        run: |
          VERSION=cyclonus make azure-npm-image




