name: Cyclonus Network Policy Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'npm/**'
      - '.github/**'
      - 'test/**'
  schedule:
    # run once a day at midnight
    - cron: '0 0 * * *'

env:
  PROFILE: v1-default

jobs:
  cyclonus-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # run cyclonus tests in parallel for NPM with the given ConfigMaps
        profile: [v1-default.yaml]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: ./test/kind/kind.yaml
          name: npm-kind

      - name: Check Kind
        run: |
          kubectl get po -owide -A

      - name: Make NPM image
        run: |
          make npm-image VERSION=cyclonus PLATFORM=linux/amd64 CONTAINER_BUILDER=docker
      
      - name: Install Azure NPM
        # set the ConfigMap based on the build matrix
        # currently have to restart the daemonset because changing the ConfigMap doesn't restart NPM
        run: |
          sed -i 's/mcr.microsoft.com\/containernetworking\/azure-npm:.*/acnpublic.azurecr.io\/azure-npm:cyclonus/' ./npm/azure-npm.yaml
          kind load docker-image acnpublic.azurecr.io/azure-npm:cyclonus --name npm-kind
          kubectl apply -f ./npm/azure-npm.yaml
          echo "Applying profile: $PROFILE"
          kubectl apply -f ./npm/profiles/$PROFILE.yaml
          kubectl rollout restart ds azure-npm -n kube-system
    
      - name: Check Cluster Components
        run: |
          sleep 120
          kubectl get po -owide -A
          kubectl describe ds azure-npm -n kube-system

      - name: Run Cyclonus network policy test and Fetch Logs
        run: | 
          ## write to all NPM pod logs in the background (do this in the background instead of after to make sure the logs aren't truncated)
          npmPodList=`kubectl get pods -n kube-system | grep npm | awk '{print $1}'`
          echo "Found NPM pods: $npmPodList"
          for npmPod in $npmPodList; do
            kubectl  logs -n kube-system $npmPod -f > $npmPod-logs_$PROFILE.txt &
          done

          make test-cyclonus
          # kill the background processes (the logs) that have this process' pid (i.e. $$) as a parent
          pkill -P $$
          # FIXME uncomment
          # mv ./test/cyclonus/cyclonus-test.txt ./cyclonus-test_$PROFILE.txt

      - name: 'Upload Logs'
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: |
            ./npm-logs_$PROFILE.txt
            ./cyclonus-test_$PROFILE.txt
