name: golangci-lint
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
    types:
      - checks_requested
jobs:
  generate:
    name: Generate BPF Handling Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run go generate
        run: make bpf-lib && go generate ./...

      - name: Upload generated code
        uses: actions/upload-artifact@v4
        with:
          name: generated-bpf-program-code
          path: ./bpf-prog/block-iptables/pkg/blockservice
  golangci:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.22.x', '1.23.x']
        os: [ubuntu-latest, windows-latest]
    name: Lint
    needs: generate
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Download generated code
      uses: actions/download-artifact@v4
      with:
        name: generated-bpf-program-code
        path: ./bpf-prog/block-iptables/pkg/blockservice
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61
        args: ${{ github.event_name == 'pull_request' && format('--new-from-rev=origin/{0}', github.base_ref) || '' }} --config=.golangci.yml --timeout=25m 
