pr: none
trigger: none

resources:
  pipelines:
  - pipeline: ACN-PR # Name of the pipeline resource.
    source: Azure Container Networking PR # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes
    # project: FabrikamProject # Required only if the source pipeline is in another project , Replace with LSG's project
#  Custom\Networking\ContainerNetworking\

stages:
  - stage: setup
    displayName: Setup
    jobs:
      - job: env
        displayName: Setup
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              echo "Setting up environment"
              go version
              echo "##vso[task.setvariable variable=commitID;isOutput=true]$(echo $(make revision)-$(date "+%d%H%M"))"
              echo "##vso[task.setvariable variable=cnsVersion;isOutput=true]$(CNS_VERSION)"
              echo "##vso[task.setvariable variable=cniVersion;isOutput=true]$(CNI_VERSION)"
            name: "SetEnvVars"
            displayName: "Set Environment Variables"
            condition: always()

  - template: kernel-upgrade-template.yaml
    parameters:
      name: linux_overlay
      clusterType: overlay-byocni-up
      clusterName: "kup-overlay"
      nodeCount: 2
      vmSize: Standard_B2ms
      arch: amd64

  - stage: delete_resources
    displayName: "Delete Resources"
    pool:
      name: "$(BUILD_POOL_NAME_DEFAULT)"
    condition: always()
    dependsOn:
      - linux_overlay
      - setup
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['SetEnvVars.commitID'] ]
    jobs:
      - job: delete
        displayName: Delete Cluster
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        strategy:
          matrix:
            linux_overlay:
              name: linux_overlay
              clusterName: "kup-overlay"
        steps:
          - template: ../../templates/delete-cluster.yaml
            parameters:
              name: $(name)
              clusterName: $(clusterName)-$(commitID)
              region: $(LOCATION)
